export type AdvancedQuestion = { prompt:string; options:string[]; answer:number; why:string; code?:string };
export type AdvancedStep = { id:string; title:string; summary:string; code:string; questions:AdvancedQuestion[] };

type Definition = { id:string; title:string; summary:string; code:string; correct:string; wrong:string[]; why:string };

const prompts = [
  () => `¿Cuál afirmación describe correctamente este concepto?`,
  () => `En el contexto de este concepto, ¿cuál opción es válida?`,
  () => `¿Qué resultado o comportamiento esperarías en este tema?`,
  (d:Definition) => `¿Cuál es la trampa común sobre ${d.title.toLowerCase()}?`,
  (d:Definition) => `¿Qué decisión de diseño corresponde a ${d.title.toLowerCase()}?`,
  () => `¿Qué palabra, tipo o API se relaciona directamente con este tema?`,
  (d:Definition) => `¿Qué alternativa NO sería correcta para ${d.title.toLowerCase()}?`,
  () => `Si ves el código del ejemplo, ¿qué concepto estás aplicando?`,
  (d:Definition) => `¿Qué afirmación de entrevista es correcta sobre ${d.title.toLowerCase()}?`,
  (d:Definition) => `¿Qué deberías recordar para evitar un bug en ${d.title.toLowerCase()}?`,
];

function makeQuestions(d:Definition):AdvancedQuestion[] {
  return prompts.map((makePrompt, i) => {
    const options = [d.correct, ...d.wrong].map((value, index, all) => all[(index + i) % all.length]);
    return { prompt:makePrompt(d), options, answer:options.indexOf(d.correct), why:d.why, code:i === 2 || i === 7 ? d.code : undefined };
  });
}

const definitions:Definition[] = [
 {id:"m04-declare",title:"declarar y llamar métodos",summary:"Un método encapsula una operación con nombre. Su firma combina nombre, parámetros y tipo de retorno; se invoca usando paréntesis.",code:"static int Sum(int a, int b) => a + b;\nvar total = Sum(2, 3);",correct:"Definir una operación reutilizable y llamarla con sus argumentos",wrong:["Crear siempre un objeto nuevo","Ejecutar código sin una firma","Convertir todo a dynamic"],why:"Los métodos permiten nombrar, reutilizar y probar una operación; la llamada debe respetar su firma."},
 {id:"m04-return",title:"parámetros y valores de retorno",summary:"Los parámetros reciben datos y return entrega un resultado. El tipo retornado debe coincidir con la firma, salvo conversiones válidas.",code:"static bool IsAdult(int age)\n    => age >= 18;",correct:"El método puede recibir parámetros y devolver un valor del tipo declarado",wrong:["Todo método debe devolver string","return solo sirve para loops","Los parámetros cambian de tipo en cada llamada"],why:"La firma comunica el contrato del método: entradas y salida."},
 {id:"m04-overload",title:"sobrecarga de métodos",summary:"La sobrecarga permite varios métodos con el mismo nombre si sus listas de parámetros son diferentes. El retorno por sí solo no distingue una sobrecarga.",code:"void Print(int value) {}\nvoid Print(string value) {}",correct:"Mismo nombre con parámetros diferentes",wrong:["Mismo nombre y solo retorno diferente","Dos métodos idénticos","Cambiar únicamente el nombre del archivo"],why:"El compilador selecciona la sobrecarga por cantidad, tipos y modificadores de parámetros; no por retorno."},
 {id:"m04-scope",title:"scope y variables locales",summary:"Una variable local existe dentro del bloque donde se declara y los bloques internos pueden usar nombres visibles de scopes externos.",code:"if (ready) { int local = 1; }\n// local no existe aquí",correct:"El nombre solo está disponible en su ámbito",wrong:["Toda variable local es global","El scope depende del valor","Una variable vive siempre toda la aplicación"],why:"Un scope pequeño evita usos accidentales y hace explícita la vida de los nombres."},
 {id:"m04-optional",title:"parámetros opcionales y nombrados",summary:"Los parámetros opcionales tienen un valor predeterminado. Los argumentos nombrados hacen explícita la asociación entre argumento y parámetro.",code:"void Connect(string host, int port = 443) {}\nConnect(host: \"api\");",correct:"Se puede omitir el parámetro opcional o llamarlo por nombre",wrong:["Todos los parámetros deben omitirse","El nombre es ignorado por el compilador","Los valores opcionales se calculan siempre en runtime"],why:"Los opcionales simplifican llamadas y los nombrados mejoran claridad, pero deben respetar las reglas de la firma."},
 {id:"m04-expression",title:"expression-bodied members",summary:"La sintaxis => permite expresar métodos, propiedades o constructores sencillos con una sola expresión.",code:"public int Double(int n) => n * 2;",correct:"Una forma compacta de escribir un miembro de una sola expresión",wrong:["Un lambda que siempre crea un thread","Una constante global","Una excepción automática"],why:"Expression-bodied es sintaxis; no cambia la semántica ni convierte el miembro en asíncrono."},
 {id:"m04-main",title:"el método Main",summary:"Main es un punto de entrada válido para una aplicación de consola. Puede devolver void o int y aceptar argumentos de línea de comandos.",code:"static void Main(string[] args)\n{\n    Console.WriteLine(\"Hi\");\n}",correct:"El punto de entrada de una aplicación de consola",wrong:["El constructor de toda clase","Un método que se ejecuta en cada request","Una interfaz obligatoria"],why:"El runtime usa Main como entrada cuando el proyecto no usa top-level statements."},
 {id:"m04-challenge",title:"reto de métodos",summary:"Integra firmas, sobrecarga, scope, retorno y argumentos para resolver pequeños problemas sin duplicar lógica.",code:"static int Add(int a, int b) => a + b;\nConsole.WriteLine(Add(4, 5));",correct:"Elegir una firma clara y reutilizable para resolver el problema",wrong:["Usar estado global para cada operación","Devolver object siempre","Evitar parámetros y repetir código"],why:"Un buen método tiene una responsabilidad clara, entradas explícitas y una salida verificable."},

 {id:"m05-create",title:"crear y concatenar strings",summary:"string representa texto y es inmutable. La concatenación crea un nuevo resultado; para muchas modificaciones conviene evaluar StringBuilder.",code:"var full = first + \" \" + last;",correct:"Construir una nueva cadena a partir de valores de texto",wrong:["Modificar chars de string en sitio","Convertir siempre a byte[]","Hacer que string sea mutable"],why:"Las operaciones de string producen nuevas cadenas porque string es inmutable."},
 {id:"m05-interpolation",title:"interpolación",summary:"La interpolación usa $ y expresiones entre llaves para construir texto legible, con formatos opcionales.",code:"var message = $\"Total: {total:C}\";",correct:"Insertar el valor de una expresión dentro de una cadena",wrong:["Escapar todo el contenido","Crear un char","Ejecutar SQL automáticamente"],why:"$ activa la interpolación; los formatos como :C se aplican al valor insertado."},
 {id:"m05-escape",title:"escape characters",summary:"Las secuencias de escape representan caracteres especiales como salto de línea, tabulación, comillas y barra invertida.",code:"Console.WriteLine(\"A\\nB\");",correct:"Representar un carácter especial dentro de un literal",wrong:["Convertir string en regex siempre","Eliminar la inmutabilidad","Indicar un comentario"],why:"\\n, \\t, \\\\ y \\\" tienen significados especiales en literales normales."},
 {id:"m05-compare",title:"comparar strings",summary:"La igualdad de strings compara contenido. Para ordenamiento y reglas culturales se debe elegir la comparación adecuada, a menudo con StringComparison.",code:"string.Equals(a, b, StringComparison.OrdinalIgnoreCase);",correct:"Comparar texto usando una regla explícita de igualdad",wrong:["Comparar siempre referencias con ReferenceEquals","Usar == solo para ordenar culturas","Convertir todo a char"],why:"La comparación de texto puede depender de mayúsculas, cultura y seguridad; especificar la intención evita errores."},
 {id:"m05-methods",title:"métodos de string",summary:"Length, Contains, StartsWith, Replace, Split y Substring consultan o transforman texto sin mutar la cadena original.",code:"var clean = input.Trim().ToLowerInvariant();",correct:"Cada operación devuelve un resultado y no muta el string original",wrong:["Todas cambian la cadena en sitio","Solo funcionan con ASCII","Devuelven siempre char"],why:"string es inmutable; encadenar métodos crea resultados intermedios o finales nuevos."},
 {id:"m05-parse",title:"Parse y TryParse",summary:"Parse convierte y lanza una excepción si el formato falla; TryParse devuelve false y entrega el valor por out.",code:"if (int.TryParse(text, out var number))\n    Console.WriteLine(number);",correct:"TryParse es preferible cuando la entrada puede ser inválida",wrong:["TryParse siempre lanza","Parse nunca falla","Cast convierte cualquier texto"],why:"TryParse permite manejar entrada inválida como una condición normal."},
 {id:"m05-builder",title:"StringBuilder",summary:"StringBuilder es útil para muchas modificaciones de texto porque mantiene un búfer mutable y evita crear tantas cadenas intermedias.",code:"var sb = new StringBuilder();\nsb.Append(\"A\").Append(\"B\");",correct:"Acumular muchas modificaciones de texto de forma eficiente",wrong:["Reemplazar todos los strings pequeños","Hacer texto inmutable","Serializar JSON automáticamente"],why:"StringBuilder es una herramienta de rendimiento; para pocas concatenaciones, string suele ser suficiente."},
 {id:"m05-challenge",title:"reto de strings",summary:"Combina limpieza, comparación, formato y parsing para procesar entradas de usuario de forma predecible.",code:"var input = \"  42 \".Trim();\nvar ok = int.TryParse(input, out var value);",correct:"Validar y transformar texto sin asumir que siempre tiene formato válido",wrong:["Usar Parse sin validar siempre","Comparar solo referencias","Mutar string por índice"],why:"El código robusto trata la entrada como datos potencialmente inválidos y conserva una intención clara."},

 {id:"m06-class",title:"qué es una clase",summary:"Una clase es un tipo de referencia que define estado y comportamiento. new crea una instancia y la variable contiene una referencia.",code:"class User { public string Name { get; set; } }\nvar user = new User();",correct:"Un molde de referencia para crear objetos con miembros",wrong:["Un valor primitivo","Una función global","Un namespace ejecutable"],why:"Las clases agrupan datos y operaciones; sus instancias viven como objetos y pueden compartir referencia."},
 {id:"m06-members",title:"campos y propiedades",summary:"Los campos almacenan datos directamente. Las propiedades exponen acceso controlado con get y set, y pueden validar o encapsular reglas.",code:"public string Name { get; private set; }",correct:"Una propiedad puede controlar cómo se lee o asigna un dato",wrong:["Una propiedad es siempre un campo público","get ejecuta el constructor","private set permite escribir desde cualquier lugar"],why:"Las propiedades son una frontera de encapsulación; un setter privado restringe la mutación externa."},
 {id:"m06-constructors",title:"constructores",summary:"Un constructor inicializa una instancia y se ejecuta al usar new. Puede estar sobrecargado y encadenarse con this o base.",code:"public User(string name) { Name = name; }",correct:"Inicializar el estado al crear un objeto",wrong:["Destruir el objeto","Ejecutarse una vez por aplicación","Ser heredado como un método normal"],why:"Los constructores no se heredan y preparan invariantes de la instancia."},
 {id:"m06-new",title:"crear objetos",summary:"new invoca un constructor y devuelve una instancia. Un inicializador de objeto puede asignar propiedades accesibles inmediatamente.",code:"var user = new User { Name = \"Ada\" };",correct:"Crear una instancia y opcionalmente inicializar propiedades",wrong:["Declarar una interfaz","Convertir una clase en static","Copiar siempre por valor"],why:"La expresión new crea el objeto; el inicializador asigna miembros después de construirlo."},
 {id:"m06-instances",title:"varias instancias",summary:"Cada instancia de una clase tiene su propio estado de instancia, mientras que los miembros static se comparten por el tipo.",code:"var a = new User();\nvar b = new User();\na.Name = \"Ada\";",correct:"Dos objetos pueden tener estados independientes",wrong:["Todas las instancias comparten cada campo","new devuelve siempre el mismo objeto","Las propiedades son globales"],why:"Los campos y propiedades de instancia pertenecen a cada objeto, no a todas las instancias."},
 {id:"m06-instance-methods",title:"métodos de instancia",summary:"Un método de instancia opera sobre el objeto actual y puede acceder a sus miembros mediante this, explícito o implícito.",code:"public void Rename(string name) => Name = name;",correct:"Un método que usa el estado de una instancia concreta",wrong:["Un método que solo puede usar static","Una propiedad automática","Un constructor obligatorio"],why:"Los métodos de instancia reciben implícitamente la instancia actual como contexto."},
 {id:"m06-challenge",title:"reto de clases",summary:"Diseña una clase con estado válido, propiedades protegidas y métodos que expresen las operaciones permitidas.",code:"var account = new Account(100);\naccount.Deposit(25);",correct:"Proteger invariantes y exponer operaciones claras",wrong:["Hacer todos los campos públicos","Permitir saldo negativo sin regla","Usar globales para cada objeto"],why:"Una clase útil protege su estado y ofrece una API pequeña que mantiene sus reglas."},

 {id:"m07-value-ref",title:"value types vs reference types",summary:"Los value types copian su valor al asignarse. Los reference types copian la referencia; dos variables pueden apuntar al mismo objeto.",code:"var a = new List<int>();\nvar b = a;\nb.Add(1);",correct:"Con una clase o lista, a y b pueden referirse al mismo objeto",wrong:["Siempre se copia toda la lista","List es un value type","Las referencias son siempre inmutables"],why:"La diferencia afecta copias, aliasing y mutaciones observables."},
 {id:"m07-pass-value",title:"pasar parámetros por valor",summary:"Por defecto, C# pasa parámetros por valor. En reference types se copia la referencia, por lo que el método aún puede mutar el objeto apuntado.",code:"void Add(List<int> xs) => xs.Add(1);",correct:"Se copia la referencia, no el objeto completo",wrong:["Todo parámetro se pasa por referencia con ref","Nunca se puede mutar el objeto","Se clona la lista automáticamente"],why:"Pasar una referencia por valor permite mutar el objeto, pero reasignar el parámetro no cambia la variable del llamador."},
 {id:"m07-ref-out-in",title:"ref, out e in",summary:"ref requiere inicialización, out debe asignarse dentro del método e in pasa una referencia de solo lectura. Son contratos explícitos.",code:"bool ok = int.TryParse(text, out var number);",correct:"out permite que el método produzca un valor adicional",wrong:["out exige valor inicial","ref ignora la variable del llamador","in permite modificar el argumento"],why:"Cada modificador cambia las reglas de entrada y salida; deben usarse con una razón clara."},
 {id:"m07-string-ref",title:"strings como reference types",summary:"string es reference type, pero su inmutabilidad hace que operaciones como concatenar devuelvan una nueva cadena en lugar de alterar la anterior.",code:"var a = \"A\";\nvar b = a;\nb += \"B\";",correct:"b recibe una nueva string y a permanece \"A\"",wrong:["a cambia a \"AB\" siempre","string es value type","b modifica chars internos"],why:"La referencia se copia, pero el objeto string no se modifica; se crea otro valor de texto."},
 {id:"m07-enums",title:"enums",summary:"Un enum define nombres para un conjunto de valores integrales. Puede convertirse a su tipo subyacente, pero conviene validar valores externos.",code:"enum Status { Draft, Published }\nStatus s = Status.Draft;",correct:"Nombrar estados relacionados de forma tipada",wrong:["Guardar cualquier texto sin validación","Crear herencia múltiple","Reemplazar todas las clases"],why:"Los enums mejoran legibilidad, aunque sus valores subyacentes pueden contener números no declarados."},
 {id:"m07-structs",title:"structs",summary:"Un struct es un value type apropiado para datos pequeños cuyo valor representa la entidad. No admite herencia de clases, pero puede implementar interfaces.",code:"readonly struct Point(int x, int y);",correct:"Un tipo de valor que se copia y puede implementar interfaces",wrong:["Una clase con herencia completa","Siempre mejor que class","Un reference type mutable por defecto"],why:"Elegir struct requiere considerar tamaño, copias, mutabilidad y semántica de valor."},
 {id:"m07-nullable",title:"nullable value types",summary:"T? para un value type permite representar un valor o null. HasValue y Value, o pattern matching, permiten acceder con seguridad.",code:"int? age = null;\nvar text = age?.ToString() ?? \"unknown\";",correct:"int? puede contener un entero o null",wrong:["int ya contiene null siempre","T? elimina todos los null","Nullable solo sirve para strings"],why:"Nullable<T> modela la ausencia de un value type sin inventar un valor especial."},
 {id:"m07-challenge",title:"reto de memoria",summary:"Predice copias, aliasing, boxing y nullability para evitar sorpresas al pasar valores y referencias entre métodos.",code:"int x = 1;\nvar y = x;\ny++;\nConsole.WriteLine(x);",correct:"Analizar si se copió el valor o la referencia antes de predecir el resultado",wrong:["Asumir que todo se comparte","Asumir que todo se clona","Ignorar nullability"],why:"La semántica de copia depende del tipo; es una pregunta clásica de entrevistas."},

 {id:"m08-namespace",title:"namespaces y using",summary:"Los namespaces organizan nombres y reducen colisiones. using permite referirse a tipos sin escribir siempre su nombre completamente calificado.",code:"using System.Collections.Generic;\nList<int> values = [];",correct:"Organizar tipos y simplificar sus nombres en un archivo",wrong:["Importar paquetes npm","Crear una instancia","Hacer un método async"],why:"using no copia ni ejecuta código; resuelve nombres de tipos y puede declarar disposiciones."},
 {id:"m08-static",title:"clases y miembros static",summary:"Un miembro static pertenece al tipo, no a una instancia. Una static class no puede instanciarse y solo contiene miembros static.",code:"static class MathTools { public static int Twice(int n) => n * 2; }",correct:"Acceder a un miembro a través del tipo sin crear instancia",wrong:["Compartir automáticamente todos los campos de instancia","Permitir herencia de static class","Guardar estado por usuario"],why:"static es apropiado para comportamiento sin estado de instancia; el estado global debe usarse con cuidado."},
 {id:"m08-null",title:"null y nullable reference types",summary:"null indica ausencia de referencia. Las anotaciones nullable ayudan al compilador a advertir posibles null, pero no agregan validación runtime por sí solas.",code:"string? name = null;\nConsole.WriteLine(name?.Length);",correct:"? expresa que una referencia puede ser null y ?. evita acceso directo",wrong:["? garantiza que nunca será null","null es un string vacío","El compilador lanza todas las excepciones"],why:"Nullable reference types son análisis estático; el programa aún debe validar entradas en runtime."},
 {id:"m08-gc",title:"garbage collection",summary:"El GC administra memoria de objetos administrados y recupera objetos que ya no son alcanzables. No reemplaza liberar recursos externos como archivos.",code:"using var stream = File.OpenRead(path);",correct:"El GC recupera memoria administrada, pero IDisposable maneja recursos externos",wrong:["GC cierra siempre sockets inmediatamente","GC elimina toda memoria nativa","GC se ejecuta al llamar Collect únicamente"],why:"La memoria y los recursos externos tienen ciclos de vida diferentes; using/Dispose es determinista."},
 {id:"m08-library",title:"class libraries",summary:"Una class library empaqueta tipos reutilizables en un ensamblado, normalmente DLL, que otros proyectos pueden referenciar.",code:"dotnet new classlib -n Shared\ndotnet add App reference Shared",correct:"Separar código reutilizable para referenciarlo desde otros proyectos",wrong:["Crear una base de datos","Publicar solo una página HTML","Reemplazar el runtime"],why:"Las librerías permiten compartir dominio, utilidades o contratos sin duplicar código."},
 {id:"m08-records",title:"records y record structs",summary:"Los records ofrecen igualdad por valor, una representación útil para datos y sintaxis with. record class es referencia; record struct es valor.",code:"public record User(int Id, string Name);\nvar copy = user with { Name = \"Lin\" };",correct:"Modelar datos con igualdad basada en valores y copias no destructivas",wrong:["Obtener herencia de structs","Hacer todas las propiedades mutables","Comparar siempre por referencia"],why:"Records reducen código ceremonial para modelos de datos y expresan semántica de valor."},
 {id:"m08-compare",title:"class vs struct vs record",summary:"class suele modelar identidad y referencia; struct valores pequeños; record datos cuya igualdad depende del contenido. La elección es semántica, no de moda.",code:"class Entity { public int Id; }\nrecord Point(int X, int Y);",correct:"Elegir según identidad, semántica de valor, tamaño y mutabilidad",wrong:["record siempre reemplaza class","struct siempre es más rápido","class y struct son idénticos"],why:"La diferencia afecta igualdad, copias, herencia y comportamiento de memoria."},
 {id:"m08-challenge",title:"reto de diseño de tipos",summary:"Selecciona class, struct, record o static con una razón explícita: identidad, datos, tamaño, ciclo de vida y comportamiento.",code:"public record Money(decimal Amount, string Currency);",correct:"Usar un record cuando la igualdad por datos expresa el dominio",wrong:["Usar static para cada modelo","Usar struct mutable gigante","Elegir por el nombre solamente"],why:"Un tipo comunica reglas del dominio; la semántica correcta evita bugs de igualdad y mutación."},

 {id:"m09-array",title:"arrays unidimensionales",summary:"Un array tiene longitud fija y almacena elementos del mismo tipo. Sus índices comienzan en cero y se accede con [] .",code:"int[] values = [10, 20, 30];\nConsole.WriteLine(values[0]);",correct:"Una colección indexada de tamaño fijo",wrong:["Una lista cuyo tamaño cambia automáticamente","Un diccionario por clave","Un conjunto sin orden"],why:"Los arrays son simples y eficientes cuando el tamaño o la estructura es conocida."},
 {id:"m09-multi",title:"arrays multidimensionales",summary:"Los arrays rectangulares y dentados representan distintas estructuras. Un array dentado es un array cuyos elementos son otros arrays.",code:"int[,] matrix = new int[2, 3];\nint[][] jagged = [ [1], [2, 3] ];",correct:"[,] representa rectangular y [][] representa dentado",wrong:["Ambos son exactamente lo mismo","[,] es un Dictionary","[][] no puede variar por fila"],why:"La sintaxis comunica si todas las filas comparten dimensiones o si cada fila puede variar."},
 {id:"m09-list",title:"List<T>",summary:"List<T> es una colección genérica redimensionable e indexada. Add, Remove y Contains operan sobre sus elementos según igualdad.",code:"var numbers = new List<int> { 1, 2 };\nnumbers.Add(3);",correct:"Una secuencia ordenada que puede crecer y admite índice",wrong:["Una clave única sin duplicados","Un array de longitud fija","Un stream asíncrono"],why:"List<T> es una opción general para colecciones ordenadas y mutables."},
 {id:"m09-dictionary",title:"Dictionary<TKey,TValue>",summary:"Dictionary asocia claves únicas con valores y ofrece búsquedas por clave. TryGetValue evita asumir que una clave existe.",code:"var ages = new Dictionary<string,int>();\nages[\"Ada\"] = 36;",correct:"Buscar un valor mediante una clave única",wrong:["Permitir claves duplicadas sin regla","Ordenar siempre por valor","Acceder solo por índice entero"],why:"La clave identifica el valor; conviene decidir cómo manejar claves ausentes y duplicadas."},
 {id:"m09-hashset",title:"HashSet<T>",summary:"HashSet representa un conjunto de elementos únicos y está optimizado para pertenencia. No debe usarse si el orden o duplicados son esenciales.",code:"var tags = new HashSet<string>();\ntags.Add(\"csharp\");",correct:"Mantener elementos sin duplicados y consultar pertenencia",wrong:["Conservar duplicados en orden de inserción garantizado","Mapear claves a valores","Indexar por posición"],why:"HashSet expresa semántica de conjunto y usa igualdad/hash del tipo."},
 {id:"m09-enumerable",title:"IEnumerable<T>",summary:"IEnumerable<T> representa algo que puede enumerarse. Muchas operaciones LINQ sobre él son diferidas hasta que se recorre o materializa.",code:"IEnumerable<int> query = values.Where(x => x > 0);",correct:"Una secuencia que puede recorrerse con foreach",wrong:["Una base de datos obligatoria","Una lista siempre materializada","Un tipo que permite indexar siempre"],why:"IEnumerable no garantiza índice ni evaluación inmediata; expresa capacidad de enumeración."},
 {id:"m09-choice",title:"elegir la colección correcta",summary:"La colección se elige por acceso, unicidad, orden, mutabilidad y rendimiento esperado, no solo por costumbre.",code:"Dictionary<int,User> byId = ...;\nList<User> ordered = ...;",correct:"Seleccionar List, Dictionary, HashSet o array según la operación dominante",wrong:["Usar List para toda búsqueda por clave","Usar HashSet cuando importan duplicados","Usar array cuando el tamaño cambia mucho"],why:"La estructura correcta hace explícita la intención y evita trabajo innecesario."},
 {id:"m09-challenge",title:"reto de colecciones",summary:"Combina índices, claves, unicidad y enumeración para modelar datos reales y elegir operaciones seguras.",code:"if (byId.TryGetValue(id, out var user))\n    Console.WriteLine(user.Name);",correct:"Usar la operación que expresa la garantía que necesitas",wrong:["Acceder a cualquier clave sin comprobar","Eliminar duplicados siempre","Convertir todo a object"],why:"Las colecciones tienen contratos distintos; las preguntas de entrevista suelen explorar esas diferencias."},

 {id:"m10-oop",title:"principios de orientación a objetos",summary:"La POO organiza estado y comportamiento en tipos. Encapsulación, abstracción, herencia y polimorfismo son ideas relacionadas, no simples palabras clave.",code:"public abstract class Shape { public abstract double Area(); }",correct:"Modelar responsabilidades y colaboraciones entre objetos",wrong:["Usar una clase por cada variable","Hacer todo heredable","Evitar contratos y pruebas"],why:"La POO es una forma de organizar el diseño; una buena solución evita acoplamiento accidental."},
 {id:"m10-encapsulation",title:"encapsulación",summary:"Encapsular es proteger invariantes y ocultar detalles internos, exponiendo operaciones o propiedades que mantengan reglas válidas.",code:"private decimal balance;\npublic void Deposit(decimal amount) { if (amount > 0) balance += amount; }",correct:"Controlar cómo cambia el estado interno",wrong:["Hacer todos los campos public","Ocultar el nombre de la clase","Usar herencia para cada regla"],why:"La encapsulación concentra validaciones y evita que cualquier consumidor rompa el estado."},
 {id:"m10-access",title:"private, protected e internal",summary:"private limita al tipo; protected incluye derivados; internal permite el mismo ensamblado. public expone a cualquier consumidor permitido.",code:"protected void Reset() {}\ninternal class Helper {}",correct:"Elegir el modificador según quién debe acceder",wrong:["protected significa público","internal significa accesible desde Internet","private permite cualquier clase"],why:"Los modificadores de acceso son parte del diseño y reducen superficie accidental."},
 {id:"m10-inheritance",title:"herencia",summary:"Una clase derivada reutiliza y especializa una clase base. C# permite una sola clase base directa, aunque sí múltiples interfaces.",code:"class Dog : Animal { }",correct:"Expresar una relación Is-A y reutilizar comportamiento base",wrong:["Compartir estado sin relación","Heredar de varias clases base","Convertir composición en interfaz"],why:"La herencia debe representar especialización real; si no, composición suele ser más flexible."},
 {id:"m10-derived",title:"base y derived classes",summary:"La clase derivada puede llamar al constructor base con base(...), usar miembros protegidos y sobrescribir miembros virtuales con override.",code:"class Dog : Animal { public Dog() : base(\"dog\") {} }",correct:"Inicializar la parte base y extender el comportamiento derivado",wrong:["Heredar constructores automáticamente","Acceder a private base directamente","Sobrescribir sin virtual o abstract"],why:"Los constructores no se heredan y la visibilidad controla qué puede usar la clase derivada."},
 {id:"m10-isa",title:"relación Is-A",summary:"Is-A describe sustitución: un objeto derivado puede usarse donde se espera su base. Has-A describe composición y no debe confundirse.",code:"Animal animal = new Dog();\nanimal.Speak();",correct:"Un Dog es un Animal y puede sustituirlo en ese contrato",wrong:["Un Dog contiene un Animal siempre","Todo campo implica herencia","Is-A significa igualdad"],why:"La relación Is-A es conceptual y debe ser válida para todos los casos del dominio."},
 {id:"m10-composition",title:"composition over inheritance",summary:"La composición construye objetos combinando colaboradores. Suele reducir acoplamiento y permite cambiar comportamiento por inyección.",code:"class Car { private readonly IEngine engine; }",correct:"Un Car tiene un motor y delega responsabilidades",wrong:["Car hereda de Engine siempre","Composition significa static","Solo sirve para structs"],why:"La composición expresa Has-A y facilita reemplazar una dependencia sin cambiar jerarquías."},
 {id:"m10-challenge",title:"reto de encapsulación",summary:"Diseña un pequeño modelo decidiendo qué ocultar, qué exponer y cuándo usar herencia, interfaz o composición.",code:"public sealed class Invoice\n{\n    public decimal Total { get; private set; }\n}",correct:"Exponer un contrato pequeño y proteger las invariantes",wrong:["Publicar todos los detalles internos","Usar herencia por defecto","Permitir mutación sin validación"],why:"El diseño OO se evalúa por responsabilidades, acoplamiento y facilidad de cambio, no por cantidad de clases."},
];

const sq=(prompt:string,options:string[],answer:number,why:string,code=""):AdvancedQuestion=>({prompt,options,answer,why,code});

// Módulo 4: preguntas escritas de forma explícita para evaluar código y no reconocer definiciones vagas.
const preciseM04:Record<string,AdvancedQuestion[]>={
 "m04-declare":[
  sq("¿Qué valor imprime la llamada a Sum?",["5","23","Error de compilación","0"],0,"Sum recibe 2 y 3, los suma y retorna 5.","static int Sum(int a, int b) => a + b;\nConsole.WriteLine(Sum(2, 3));"),
  sq("¿Cuál es el tipo de retorno declarado por este método?",["int","void","Task<int>","var"],0,"La palabra int antes del nombre indica el tipo de retorno."),
  sq("¿Qué parte identifica al método en esta declaración?",["Sum","static","int","a + b"],0,"Sum es el nombre usado para invocarlo; static y int describen otras partes."),
  sq("¿Qué llamada compila con esta firma: Sum(int a, int b)?",["Sum(2, 3)","Sum(2)","Sum(\"2\", 3)","Sum()"],0,"La firma exige exactamente dos argumentos compatibles con int."),
  sq("¿Qué ocurre si se elimina return de un método que devuelve int y usa bloque?",["No compila porque debe producir un int","Devuelve 0 automáticamente","Se convierte en void","Solo falla si se llama"],0,"Todo camino válido de un método int debe devolver un entero."),
  sq("¿Qué imprime este método cuando se llama con 4?",["8","4","16","No compila"],0,"La expresión devuelve n * 2: 4 * 2 es 8.","static int Double(int n) => n * 2;\nConsole.WriteLine(Double(4));"),
  sq("¿Cuál diferencia existe entre declarar e invocar un método?",["Declarar define la firma; invocar ejecuta su cuerpo","Invocar siempre crea una clase","Declarar ejecuta inmediatamente","No existe diferencia"],0,"La declaración crea el contrato; una llamada solicita su ejecución."),
  sq("¿Qué modificador permite llamar a este método mediante MathTools.Sum()?",["static","private","readonly","virtual"],0,"Un miembro static pertenece al tipo y se accede por el nombre de la clase."),
  sq("¿Qué argumento llega a b en Sum(7, 9)?",["9","7","b queda null","El método no recibe argumentos"],0,"Los argumentos posicionales se asignan de izquierda a derecha."),
  sq("¿Cuál línea declara correctamente un método sin resultado?",["void Log(string message) { }","int Log(string message) { }","return Log(string message);","method Log => void"],0,"void indica que el método no devuelve un valor."),
 ],
 "m04-return":[
  sq("¿Qué imprime IsAdult(20)?",["True","False","20","Error"],0,"20 >= 18 es true y el método retorna ese bool.","static bool IsAdult(int age) => age >= 18;\nConsole.WriteLine(IsAdult(20));"),
  sq("¿Qué tipo debe retornar un método declarado como bool?",["bool","int siempre","void siempre","object obligatoriamente"],0,"La expresión retornada debe ser compatible con bool."),
  sq("¿Qué ocurre al ejecutar return dentro de un método?",["Termina el método y entrega el valor","Repite el método","Solo sale de un if","Cambia el tipo de retorno"],0,"return finaliza la ejecución del método actual."),
  sq("¿Cuál firma recibe una edad y devuelve si es válida?",["bool IsValid(int age)","void IsValid(bool age)","int IsValid()","string IsValid(int age, bool result)"],0,"El parámetro es int y la respuesta natural es bool."),
  sq("¿Qué imprime este código?",["3","2","1","Error"],0,"El return entrega 1 + 2, es decir 3.","static int Add(int x, int y) { return x + y; }\nConsole.WriteLine(Add(1, 2));"),
  sq("¿Qué error hay en `int Get() { return \"4\"; }`?",["string no es convertible implícitamente a int","Falta static","return no puede usarse en métodos","int solo acepta 0"],0,"El valor retornado debe ser int o convertirse explícitamente."),
  sq("¿Cuál es la diferencia entre un parámetro y el valor retornado?",["El parámetro entra al método; el retorno sale del método","Ambos siempre salen","El parámetro es el nombre de la clase","El retorno solo sirve para void"],0,"La firma describe datos de entrada y resultado de salida."),
  sq("¿Qué imprime `Max(3, 8)` si retorna `a > b ? a : b`?",["8","3","true","No compila"],0,"La condición es falsa y se selecciona b, que vale 8.","static int Max(int a,int b) => a > b ? a : b;"),
  sq("¿Cuál método puede usarse dentro de una expresión?",["Uno que devuelve un valor","Solo uno void","Solo un constructor","Uno sin parámetros siempre"],0,"Un método con retorno puede aportar un valor a otra expresión."),
  sq("¿Qué pasa si un método int tiene un camino sin return?",["Error de compilación","Devuelve null","Devuelve 0","Se corrige en runtime"],0,"El compilador exige retorno en todos los caminos posibles."),
 ],
 "m04-overload":[
  sq("¿Por qué estas dos declaraciones son una sobrecarga válida?",["Difieren en el tipo del parámetro","Difieren solo en el retorno","Tienen nombres distintos","Una es una propiedad"],0,"Print(int) y Print(string) tienen listas de parámetros distintas.","void Print(int value) {}\nvoid Print(string value) {}"),
  sq("¿Qué llamada selecciona Print(string)?",["Print(\"42\")","Print(42)","Print()","Print(true, false)"],0,"El literal entre comillas es string."),
  sq("¿Se puede sobrecargar cambiando únicamente el tipo de retorno?",["No","Sí siempre","Solo con static","Solo en records"],0,"El retorno no forma parte de la firma usada para resolver la llamada."),
  sq("¿Qué imprime `Format(5)` si existen Format(int) => \"int\" y Format(object) => \"object\"?",["int","object","Ambiguo siempre","Error de runtime"],0,"La conversión identity a int es mejor que convertir a object.","string Format(int x)=>\"int\";\nstring Format(object x)=>\"object\";"),
  sq("¿Qué ocurre si dos overloads son igualmente aplicables?",["Error de ambigüedad","Se elige el primero escrito","Se elige el último","Se ejecutan ambos"],0,"El compilador no puede seleccionar una única firma."),
  sq("¿Cuál conjunto representa overloads válidos?",["Save(string) y Save(string, bool)","Save(int) y Save(int) idénticos","Save() y Save() idénticos","Save() y una propiedad Save"],0,"La cantidad de parámetros puede diferenciar overloads."),
  sq("¿Qué cambio NO crea una sobrecarga?",["Cambiar solo `int` por `long` en el retorno","Agregar un parámetro","Cambiar el tipo de un parámetro","Cambiar la cantidad de parámetros"],0,"Dos métodos no pueden diferenciarse solamente por el tipo de retorno."),
  sq("¿Qué llamada usa el overload con dos parámetros?",["Calculate(2, 3)","Calculate(2)","Calculate()","Calculate(\"2\")"],0,"La cantidad y tipos deben coincidir con la firma de dos argumentos."),
  sq("¿Qué beneficio aporta una sobrecarga bien diseñada?",["Mismo concepto con entradas compatibles distintas","Evita toda validación","Convierte métodos en variables","Permite herencia múltiple"],0,"Mantiene un nombre coherente sin obligar a una única forma de entrada."),
  sq("¿Qué pasa con `M(1)` si existen M(long) y M(double)?",["Se elige M(long) por la conversión numérica mejor","Siempre es ambiguo","Se elige double siempre","No compila porque 1 no es número"],0,"Un int se convierte implícitamente a long con una conversión mejor que a double en este caso."),
 ],
 "m04-scope":[
  sq("¿Qué imprime el código?",["1","0","Error porque local no existe","null"],0,"local existe dentro del bloque y se suma a total.","int total=0;\n{ int local=1; total += local; }\nConsole.WriteLine(total);"),
  sq("¿Qué ocurre al usar `local` después de la llave de su bloque?",["Error de compilación: está fuera de scope","Se obtiene 0","Se vuelve global","Se crea otra local automáticamente"],0,"Una variable local solo es visible dentro de su bloque."),
  sq("¿Qué variable puede leer un bloque interno?",["Una variable visible del bloque externo","Solo variables declaradas después","Ninguna","Solo variables static"],0,"Los scopes internos pueden leer nombres externos visibles."),
  sq("¿Qué imprime este código?",["2","1","Error","0"],0,"El local interno sombrea al externo; Console.WriteLine dentro del bloque usa 2.","int value=1;\n{ int inner=2; Console.WriteLine(inner); }"),
  sq("¿Para qué sirve declarar un bloque `{ }` sin if?",["Crear un scope local","Crear una clase anónima","Forzar un thread","No tiene ningún efecto"],0,"Las llaves pueden limitar la vida y visibilidad de variables locales."),
  sq("¿Qué palabra termina el método y puede devolver un valor?",["return","break","continue","scope"],0,"return sale del método; break y continue se relacionan con loops."),
  sq("¿Qué error ocurre aquí?",["`result` se usa fuera del bloque donde fue declarado","Falta un using","int no puede estar en if","El if siempre exige else"],0,"result deja de estar visible al cerrar la llave.","if (ok) { int result=1; }\nConsole.WriteLine(result);"),
  sq("¿Qué principio reduce errores de scope?",["Declarar una variable lo más cerca posible de su uso","Declarar todo global","Usar dynamic para todos","Evitar las llaves"],0,"Un scope pequeño hace más claro dónde puede usarse el nombre."),
  sq("¿Qué ocurre con una variable declarada en un `for`?",["Normalmente solo existe en el for","Se vuelve global","Solo existe en el siguiente método","Siempre se convierte en static"],0,"El scope de la variable de control queda limitado al for."),
  sq("¿Qué diferencia hay entre `return` y `break`?",["return sale del método; break sale del loop más cercano","Ambos salen siempre de la aplicación","break devuelve un valor","return solo sirve en switch"],0,"Cada palabra controla un nivel distinto de flujo."),
 ],
 "m04-optional":[
  sq("¿Qué imprime `Connect(\"api\")` con port opcional 443?",["443","0","Error porque falta port","null"],0,"El valor predeterminado de port es 443.","void Connect(string host,int port=443)=>Console.WriteLine(port);\nConnect(\"api\");"),
  sq("¿Qué llamada usa argumentos nombrados correctamente?",["Connect(port: 8443, host: \"api\")","Connect(8443: port, \"api\")","Connect(host = \"api\")","Connect(named \"api\")"],0,"La sintaxis es nombreParametro: valor y permite cambiar el orden cuando corresponde."),
  sq("¿Dónde debe estar un parámetro opcional respecto a uno obligatorio?",["Después de los obligatorios","Antes de todos siempre","Solo en otro método","No hay regla"],0,"Los parámetros opcionales deben aparecer después de los requeridos en una firma normal."),
  sq("¿Qué valor recibe `timeout` en `Run(5)` si `timeout=30`?",["30","5","null","Error"],0,"Al omitirse, se usa el valor predeterminado."),
  sq("¿Qué llamada es inválida si `void M(int x, int y=1)`?",["M()","M(5)","M(x:5)","M(5, 2)"],0,"x es obligatorio, por lo que M() no compila."),
  sq("¿Qué ventaja principal tiene un argumento nombrado?",["Hace explícita la relación entre valor y parámetro","Convierte el método en async","Evita el tipo del argumento","Crea una sobrecarga"],0,"El nombre mejora legibilidad y reduce errores con varios argumentos del mismo tipo."),
  sq("¿Qué ocurre si se omite un parámetro sin valor predeterminado?",["Error de compilación","Se usa null siempre","Se usa 0 siempre","El método no se ejecuta pero compila"],0,"Los parámetros obligatorios deben recibir un argumento."),
  sq("¿Qué valor imprime `M(label: \"ok\")` si label es opcional `\"none\"`?",["ok","none","null","Error"],0,"Un argumento nombrado suministrado reemplaza el valor predeterminado."),
  sq("¿Qué orden es válido al mezclar posicionales y nombrados?",["Los posicionales primero y luego los nombrados","Nombrados siempre antes","Solo nombrados","Nunca se pueden mezclar"],0,"C# permite argumentos posicionales antes de argumentos nombrados válidos."),
  sq("¿Qué riesgo tienen demasiados parámetros opcionales?",["Pueden ocultar configuraciones importantes y crear llamadas ambiguas","Hacen el método abstracto","Eliminan la sobrecarga","Siempre provocan boxing"],0,"La comodidad no debe sustituir una API clara."),
 ],
 "m04-expression":[
  sq("¿Qué valor devuelve `Double(6)`?",["12","6","36","void"],0,"La expresión n * 2 devuelve 12.","static int Double(int n) => n * 2;"),
  sq("¿Qué sintaxis es equivalente a `int Square(int n) => n*n;`?",["int Square(int n) { return n*n; }","int Square(int n) { n*n; }","void Square(int n) => return n*n;","int Square => n*n;"],0,"La forma de bloque necesita return explícito."),
  sq("¿Qué miembro puede escribirse expression-bodied?",["Un método o propiedad de una sola expresión","Solo una variable local","Solo una clase","Solo un namespace"],0,"La sintaxis => aplica a varios miembros expresables de forma compacta."),
  sq("¿Qué imprime `Name => first + \" \" + last` con Ada Lovelace?",["Ada Lovelace","first last","null","No compila"],0,"La propiedad devuelve la concatenación evaluada."),
  sq("¿Qué significa `=>` en un miembro expression-bodied?",["La expresión es el cuerpo y su resultado es el retorno cuando aplica","Declara una lambda siempre","Indica herencia","Indica async"],0,"No implica async ni herencia; es una forma compacta de cuerpo."),
  sq("¿Qué error hay en `int Get() => { return 1; }`?",["La forma expression-bodied no usa llaves ni return","int no puede usar =>","Falta static","Los métodos no pueden retornar int"],0,"Con => se escribe directamente la expresión: `int Get() => 1;`."),
  sq("¿Qué imprime `IsEven(4)`?",["True","False","4","Error"],0,"4 % 2 es 0, por lo que la comparación es true.","bool IsEven(int n) => n % 2 == 0;"),
  sq("¿Qué ventaja aporta esta sintaxis?",["Reduce código ceremonial cuando la operación es simple","Evita validar parámetros","Hace el método más rápido siempre","Convierte retorno en dynamic"],0,"Es principalmente una mejora de legibilidad, no una optimización automática."),
  sq("¿Qué expresión devuelve la propiedad `IsEmpty => Count == 0`?",["bool","int","string","void"],0,"La comparación Count == 0 produce bool."),
  sq("¿Cuándo conviene preferir un bloque normal?",["Cuando hay varias instrucciones, validaciones o control de flujo","Siempre que el método sea int","Nunca","Solo con static"],0,"El bloque comunica mejor una lógica de varias líneas."),
 ],
 "m04-main":[
  sq("¿Qué método puede ser punto de entrada de una consola tradicional?",["static void Main(string[] args)","public Start()","void Execute(string[] args)","static Entry(string args)"],0,"Main con firma válida es un punto de entrada de consola."),
  sq("¿Qué tipo representa los argumentos recibidos desde la consola?",["string[]","int[]","object","Task<string>"],0,"Los argumentos llegan como un arreglo de cadenas."),
  sq("¿Qué imprime `args.Length` si la app se ejecuta sin argumentos?",["0","1","null","Error"],0,"Sin argumentos, el array existe y su longitud es cero.","static void Main(string[] args) => Console.WriteLine(args.Length);"),
  sq("¿Qué retorno puede usar Main para indicar un código de salida?",["int","string","bool únicamente","double"],0,"Main puede retornar int; 0 suele indicar éxito."),
  sq("¿Qué firma representa un Main asíncrono válido moderno?",["static async Task Main()","static async void Main()","static async int Main()","async Main()"],0,"Un punto de entrada async retorna Task o Task<int>, no void ni int directo."),
  sq("¿Qué ocurre con top-level statements?",["El compilador genera implícitamente el punto de entrada","Se elimina Main del runtime","Solo funciona en librerías","Convierte C# en script sin compilación"],0,"Top-level statements simplifican el archivo, pero sigue existiendo un entry point generado."),
  sq("¿Qué valor suele significar código de salida 0?",["Ejecución exitosa","Error de compilación","Argumento faltante siempre","Excepción no controlada"],0,"Por convención, 0 indica éxito."),
  sq("¿Qué sucede si el proyecto tiene dos Main válidos?",["El compilador necesita que se seleccione el entry point","Se ejecutan ambos","Se elige el último archivo","Se convierten en overloads"],0,"Dos puntos de entrada generan ambigüedad salvo configuración explícita."),
  sq("¿Qué contiene `args[0]`?",["El primer argumento proporcionado","El nombre del método Main","Siempre null","El código de salida"],0,"Los índices del array contienen los argumentos; el primero es args[0]."),
  sq("¿Dónde debe estar Main en un programa con clases tradicionales?",["Dentro de un tipo, normalmente una clase o struct","En un namespace sin tipo","Dentro de un JSON","Solo en una interface"],0,"Main es un miembro de tipo, salvo que el compilador lo genere con top-level statements."),
 ],
 "m04-challenge":[
  sq("¿Qué imprime este programa?",["9","20","5","Error"],0,"Add retorna 4 + 5 y Main imprime 9.","static int Add(int a,int b)=>a+b;\nstatic void Main(){ Console.WriteLine(Add(4,5)); }"),
  sq("¿Qué firma evita aceptar una edad negativa sin ocultar la validación?",["bool TryCreate(int age, out User user)","User Create(object value)","void Create()","dynamic Create(string age)"],0,"Un patrón Try puede comunicar éxito/fallo y producir el usuario por out."),
  sq("¿Qué sobrecarga se elige para `Print(10)` si existen Print(int) y Print(string)?",["Print(int)","Print(string)","Ambas","Ninguna"],0,"10 es un int y coincide directamente con Print(int)."),
  sq("¿Qué ocurre con la variable `result` aquí?",["Solo existe dentro del if","Existe en todo Main","Es static","Se convierte en campo"],0,"Su declaración está dentro del bloque del if.","if (ok) { int result=1; }"),
  sq("¿Qué imprime `Format(value: 12)` si value es un argumento nombrado?",["12","value","null","Error siempre"],0,"El argumento nombrado se asigna al parámetro value."),
  sq("¿Qué opción expresa mejor una operación pura `Tax(decimal amount)`?",["decimal Tax(decimal amount) => amount * 0.19m;","void Tax() { global += 1; }","dynamic Tax(object x)","Tax = amount * 0.19m;"],0,"La firma recibe una entrada y retorna el resultado sin estado oculto."),
  sq("¿Qué error detecta el compilador en este método?",["No todos los caminos retornan un int","Falta una clase base","El parámetro debe ser out","El método siempre debe ser async"],0,"Si alguna rama no devuelve int, el método no cumple su contrato.","static int Grade(int score) { if(score >= 60) return 1; }"),
  sq("¿Qué opción evita modificar una lista recibida por error?",["Recibir `IReadOnlyList<int>` si solo se necesita leer","Recibir List<int> y llamar Clear","Usar dynamic","Pasar siempre ref"],0,"Una interfaz de solo lectura expresa que el método no necesita mutar la colección."),
  sq("¿Qué resultado produce `Run(5)` si `Run(int x, int retries=3)`?",["Usa retries=3","No compila","Usa retries=0","Llama una sobrecarga inexistente"],0,"El argumento opcional completa la llamada con 3."),
  sq("¿Cuál es la mejor señal de que un método necesita dividirse?",["Tiene varias responsabilidades y muchos caminos difíciles de probar","Tiene un solo parámetro","Retorna int","Es static"],0,"Separar responsabilidades mejora legibilidad, pruebas y mantenimiento."),
 ]
};

// preciseM04 se escribió originalmente con la respuesta correcta siempre en el
// índice 0 de `options` (bug real: se podía "ganar" el módulo respondiendo
// siempre la opción A, sin leer la pregunta). Esta rotación determinista
// redistribuye la posición de la respuesta correcta entre A/B/C/D sin tocar
// el texto de cada pregunta.
function shuffleQuestionOptions(question: AdvancedQuestion, shift: number): AdvancedQuestion {
  const n = question.options.length;
  const options = question.options.map((_, k) => question.options[(k + shift) % n]);
  const answer = (question.answer - shift + n) % n;
  return { ...question, options, answer };
}
const hashKey = (key: string) => key.split("").reduce((sum, char) => sum + char.charCodeAt(0), 0);
for (const key of Object.keys(preciseM04)) {
  const offset = hashKey(key);
  preciseM04[key] = preciseM04[key].map((question, qi) => shuffleQuestionOptions(question, (qi + offset) % question.options.length));
}

export const advancedSteps:AdvancedStep[] = definitions.map(d => ({ ...d, questions:preciseM04[d.id]||makeQuestions(d) }));
if (advancedSteps.some(step => step.questions.length !== 10)) throw new Error("Cada paso debe tener exactamente 10 preguntas");
