"use client";
import { useState } from "react";

type CourseModule={id:string;title:string;duration:string;summary:string;steps:string[];kind:"C#"|".NET"};
export const curriculum:CourseModule[]=[
 {id:"m01",kind:"C#",title:"Curso y entorno de trabajo",duration:"20 min",summary:"Instala .NET, crea proyectos y entiende el flujo de ejecución.",steps:["Qué son C# y .NET","Instalar el SDK y usar dotnet CLI","Crear una consola y conocer el proyecto","Compilar, ejecutar y publicar","Resumen y reto"]},
 {id:"m02",kind:"C#",title:"Sintaxis esencial de C#",duration:"54 min",summary:"Los bloques que usarás en cada programa.",steps:["Variables y constantes","Tipos integrados y tipos primitivos","Strings y caracteres","Operadores","DateTime","Conversión entre tipos","Tipado implícito con var","Reto de sintaxis"]},
 {id:"m03",kind:"C#",title:"Decisiones y ciclos",duration:"44 min",summary:"Controla el flujo de tus programas.",steps:["Booleanos y comparaciones","if / else","switch y pattern matching","while","do while","for y foreach","break y continue","Reto de control de flujo"]},
 {id:"m04",kind:"C#",title:"Métodos y alcance",duration:"45 min",summary:"Divide problemas y escribe código reutilizable.",steps:["Declarar y llamar métodos","Parámetros y valores de retorno","Sobrecarga","Scope y variables locales","Parámetros opcionales y nombrados","Expression-bodied members","El método Main","Reto de métodos"]},
 {id:"m05",kind:"C#",title:"Strings y parsing",duration:"26 min",summary:"Manipula texto de forma segura y eficiente.",steps:["Crear y concatenar strings","Interpolación","Escape characters","Comparar strings","String methods","Parse y TryParse","StringBuilder","Reto de strings"]},
 {id:"m06",kind:"C#",title:"Clases y objetos",duration:"39 min",summary:"Construye tus primeros tipos propios.",steps:["Qué es una clase","Campos y propiedades","Constructores","Crear objetos","Trabajar con varias instancias","Métodos de instancia","Reto de clases"]},
 {id:"m07",kind:"C#",title:"Value types y reference types",duration:"49 min",summary:"Entiende memoria, copias y referencias.",steps:["Value types vs reference types","Pasar parámetros por valor","ref, out e in","Strings como reference types","Enums","Structs","Nullable value types","Reto de memoria"]},
 {id:"m08",kind:"C#",title:"Namespaces, static, null y records",duration:"46 min",summary:"Organiza tipos y modela datos correctamente.",steps:["Namespaces y using","Clases y miembros static","null y nullable reference types","Garbage Collection","Class libraries","Records y record structs","class vs struct vs record","Reto de diseño"]},
 {id:"m09",kind:"C#",title:"Arrays, listas y colecciones",duration:"35 min",summary:"Guarda y transforma grupos de datos.",steps:["Arrays unidimensionales","Arrays multidimensionales","List<T>","Dictionary<TKey,TValue>","HashSet<T>","IEnumerable<T>","Elegir la colección correcta","Reto de colecciones"]},
 {id:"m10",kind:"C#",title:"POO: encapsulación e herencia",duration:"48 min",summary:"Diseña objetos con responsabilidades claras.",steps:["Principios de orientación a objetos","Encapsulación","private, protected e internal","Herencia","Base y derived classes","Relación Is-A","Composition over inheritance","Reto de encapsulación"]},
 {id:"m11",kind:"C#",title:"Polimorfismo e interfaces",duration:"52 min",summary:"Programa contra abstracciones y contratos.",steps:["Virtual y override","Polimorfismo","Abstract classes","Interfaces","Implementar varios contratos","Dependency Inversion","SOLID aplicado","Reto de diseño OO"]},
 {id:"m12",kind:"C#",title:"LINQ, lambdas y delegates",duration:"1 h 10 min",summary:"Consulta colecciones con expresiones claras.",steps:["Delegates y Action/Func","Lambdas","Where y Select","OrderBy y ThenBy","First, Single y Any","GroupBy y Join","Deferred execution","Reto LINQ"]},
 {id:"m13",kind:"C#",title:"Excepciones y archivos",duration:"50 min",summary:"Maneja errores y trabaja con el sistema de archivos.",steps:["Excepciones en C#","try / catch / finally","Crear excepciones propias","File y Directory","Leer y escribir texto","Streams","JSON básico","Reto de persistencia"]},
 {id:"m14",kind:"C#",title:"Async, await y concurrencia",duration:"1 h 05 min",summary:"Construye código asíncrono que no bloquea.",steps:["Task y Task<T>","async y await","Cancelar con CancellationToken","Manejo de errores async","Parallel y Task.WhenAll","Race conditions","ConfigureAwait","Reto asíncrono"]},
 {id:"m15",kind:"C#",title:"Testing y depuración",duration:"45 min",summary:"Verifica tu código y encuentra errores.",steps:["Debugger y breakpoints","Unit tests","Arrange, Act, Assert","Moq y test doubles","Tests parametrizados","Cobertura y calidad","Reto de testing"]},
 {id:"n01",kind:".NET",title:".NET moderno y arquitectura de proyectos",duration:"50 min",summary:"Entiende SDK, runtimes, soluciones y dependencias.",steps:["SDK, runtime y workloads","csproj y TargetFramework","Solutions y project references","NuGet","dotnet tool","Configuración por entorno","Build y publish","Reto de estructura"]},
 {id:"n02",kind:".NET",title:"ASP.NET Core desde cero",duration:"1 h 15 min",summary:"Crea aplicaciones web con el pipeline de .NET.",steps:["Minimal APIs y Controllers","Middleware","Routing","Model binding","Dependency Injection","Configuration","Logging","Reto web"]},
 {id:"n03",kind:".NET",title:"Web APIs REST profesionales",duration:"1 h 20 min",summary:"Diseña APIs robustas y fáciles de consumir.",steps:["HTTP y REST","Endpoints y status codes","DTOs y validación","Swagger / OpenAPI","Filtros","Versionado","Rate limiting","Reto API"]},
 {id:"n04",kind:".NET",title:"Entity Framework Core y SQL",duration:"1 h 30 min",summary:"Persiste datos y trabaja con bases relacionales.",steps:["DbContext y DbSet","Migrations","Relationships","LINQ to Entities","Tracking vs NoTracking","Transacciones","Consultas eficientes","Reto de datos"]},
 {id:"n05",kind:".NET",title:"Seguridad: identidad, JWT y autorización",duration:"1 h 10 min",summary:"Protege APIs y controla acceso por roles.",steps:["Authentication vs authorization","Identity","JWT Bearer","Claims y roles","Policies","CORS y CSRF","Secretos seguros","Reto de seguridad"]},
 {id:"n06",kind:".NET",title:"Diseño limpio y patrones",duration:"1 h 20 min",summary:"Toma decisiones de arquitectura que escalan.",steps:["Clean Architecture","SOLID en servicios","Repository y Unit of Work","CQRS","MediatR","Options pattern","Observabilidad","Reto de arquitectura"]},
 {id:"n07",kind:".NET",title:"Mensajería y background services",duration:"55 min",summary:"Procesa trabajo en segundo plano y eventos.",steps:["IHostedService","BackgroundService","Queues","Health checks","Eventos de dominio","Reintentos","Idempotencia","Reto de workers"]},
 {id:"n08",kind:".NET",title:"Rendimiento y memoria",duration:"1 h",summary:"Diagnostica cuellos de botella en aplicaciones .NET.",steps:["Allocations y GC","Span<T> y Memory<T>","Caching","Async eficiente","BenchmarkDotNet","Profiling","Compilación AOT","Reto de performance"]},
 {id:"n09",kind:".NET",title:"Contenedores y despliegue",duration:"1 h 05 min",summary:"Empaqueta y publica aplicaciones reales.",steps:["Dockerfile para .NET","Docker Compose","Variables de entorno","CI/CD","Health probes","Logs en producción","Azure App Service","Reto de despliegue"]},
 {id:"n10",kind:".NET",title:"Testing de aplicaciones web",duration:"1 h",summary:"Prueba APIs, integración y componentes.",steps:["WebApplicationFactory","Integration tests","Testcontainers","Mocks vs fakes","Contract tests","Pipeline de calidad","Reto de testing web"]},
 {id:"n11",kind:".NET",title:"Preparación para entrevistas",duration:"1 h 30 min",summary:"Practica preguntas y ejercicios de nivel profesional.",steps:["C# fundamentals","POO y SOLID","LINQ y colecciones","Async y concurrencia","APIs y EF Core","Arquitectura","Live coding","Simulacro final"]},
];

export function Curriculum({onOpenModule}:{onOpenModule:(topic:string)=>void}){
 const [open,setOpen]=useState<string|null>(null);
 return <section className="curriculum"><div className="curriculum-title"><div><p className="eyebrow">PATH COMPLETO</p><h2>C# → <span>.NET profesional</span></h2><p>27 módulos · fundamentos, backend y entrevistas</p></div><span className="curriculum-badge">Ruta 2026</span></div><div className="track-label">C# FUNDAMENTALS <span>15 módulos</span></div>{curriculum.map((m,i)=><div className="curriculum-module" key={m.id}><button className="module-row" onClick={()=>setOpen(open===m.id?null:m.id)}><span className={`module-number ${m.kind===".NET"?"net-number":""}`}>{m.kind===".NET"?"N" : String(i+1).padStart(2,"0")}</span><span className="module-main"><b>{m.title}</b><small>{m.summary}</small></span><span className="module-time">{m.duration}</span><span className="module-chevron">{open===m.id?"⌃":"⌄"}</span></button>{open===m.id&&<div className="module-steps"><div className="module-steps-head"><span>{m.steps.length} pasos</span><span>{m.kind}</span></div>{m.steps.map((step,si)=><button className="step-row" key={step} onClick={()=>{if(si===m.steps.length-1&&m.kind==="C#")onOpenModule(i<2?"Todos":"POO")}}><span>{si+1}</span><span>{step}</span><small>{si===m.steps.length-1?"Reto":"Lección"}</small></button>)}</div>}</div>)}<div className="track-label net-label">.NET PROFESSIONAL <span>12 módulos</span></div></section>;
}
