"use client";

import { useState } from "react";

type EfQuestion = { area?: string; prompt: string; code: string; options: string[]; answer: number; explanation: string; clarification: string };

const efQuestions: EfQuestion[] = [
  { prompt: "¿Qué problema resuelve principalmente un ORM como Entity Framework Core?", code: "db.Users.Add(user);\nawait db.SaveChangesAsync();", options: ["Mapear objetos y operaciones de código a tablas y operaciones de base de datos", "Eliminar la necesidad de diseñar índices", "Convertir todas las consultas en memoria", "Reemplazar HTTP por SQL"], answer: 0, explanation: "Un ORM traduce entre el modelo orientado a objetos y el modelo relacional, reduciendo SQL repetitivo y centralizando el mapeo.", clarification: "ORM no significa que no debas conocer SQL: una consulta mal expresada en LINQ puede generar SQL costoso." },
  { prompt: "¿Cuál es la responsabilidad principal de `DbContext`?", code: "await using var db = new AppDbContext();\nvar users = await db.Users.ToListAsync();", options: ["Representar una sesión de trabajo, consultar entidades y coordinar cambios", "Ser una conexión global que debe vivir toda la aplicación", "Guardar automáticamente todas las tablas en memoria", "Reemplazar el servidor de base de datos"], answer: 0, explanation: "DbContext administra el modelo, la identidad de entidades, el change tracker y la interacción con la base de datos.", clarification: "En ASP.NET Core normalmente se registra scoped por request; no conviene compartir un DbContext entre requests o threads." },
  { prompt: "¿Qué representa normalmente un `DbSet<User>`?", code: "public DbSet<User> Users => Set<User>();", options: ["El conjunto consultable y persistible de entidades User", "Una lista que siempre contiene todos los usuarios", "Una tabla física independiente de User", "Un DTO sin relación con la base"], answer: 0, explanation: "DbSet expone operaciones LINQ y de persistencia para un tipo de entidad dentro del contexto.", clarification: "Consultar un DbSet no trae datos inmediatamente: la ejecución depende de operadores terminales como ToListAsync, FirstAsync o una enumeración." },
  { prompt: "¿Qué diferencia clave hay entre `IQueryable<T>` e `IEnumerable<T>` con EF Core?", code: "IQueryable<User> query = db.Users;\nvar result = await query.Where(u => u.Active).ToListAsync();", options: ["IQueryable puede traducirse y ejecutarse en el proveedor; IEnumerable opera sobre objetos ya cargados", "IEnumerable siempre consulta más rápido la base", "IQueryable solo funciona con arrays", "No existe ninguna diferencia"], answer: 0, explanation: "Mientras la consulta conserva IQueryable, EF puede traducir la expresión a SQL. Al pasar a memoria, el resto se ejecuta en .NET.", clarification: "AsEnumerable, ToList y ToArray son fronteras importantes: después de ellas, filtros posteriores pueden ejecutarse en memoria." },
  { prompt: "¿Qué significa que LINQ tenga ejecución diferida?", code: "var query = db.Users.Where(u => u.Active);\n// todavía no se ejecuta SQL\nvar users = await query.ToListAsync();", options: ["La consulta se ejecuta al materializarla o enumerarla", "La consulta nunca llega a la base", "La consulta se ejecuta al declarar la variable", "EF guarda el resultado para siempre"], answer: 0, explanation: "Construir la expresión no suele ejecutar SQL; operadores terminales como ToListAsync disparan la consulta.", clarification: "Si enumeras dos veces una consulta no materializada, puedes ejecutar dos consultas. Materializa una vez cuando necesites reutilizar el resultado." },
  { prompt: "¿Cuándo usarías `AsNoTracking()`?", code: "var products = await db.Products\n    .AsNoTracking()\n    .Where(p => p.Active)\n    .ToListAsync();", options: ["Cuando solo leerás datos y no necesitas que EF detecte cambios", "Cuando quieres actualizar entidades automáticamente", "Para crear una migración", "Para forzar una transacción distribuida"], answer: 0, explanation: "AsNoTracking evita el seguimiento de cambios y suele reducir memoria y trabajo en consultas de solo lectura.", clarification: "No lo uses por reflejo si vas a modificar y guardar esas mismas entidades: sin tracking debes adjuntar o actualizar el estado correctamente." },
  { prompt: "¿Qué hace `Include` en una consulta?", code: "var orders = await db.Orders\n    .Include(o => o.Items)\n    .ToListAsync();", options: ["Carga explícitamente una navegación relacionada", "Crea una tabla nueva", "Desactiva el tracking", "Convierte Order en DTO"], answer: 0, explanation: "Include indica a EF que también cargue una relación durante la consulta.", clarification: "Include no siempre es la mejor opción: para APIs suele ser más eficiente proyectar solo los campos necesarios con Select." },
  { prompt: "¿Qué estrategia suele evitar traer columnas innecesarias a una API?", code: "var data = await db.Users\n    .Select(u => new UserListItem(u.Id, u.Name))\n    .ToListAsync();", options: ["Proyección con Select al DTO requerido", "Traer la entidad completa y ocultar campos al final", "Usar Include para todas las navegaciones", "Llamar ToList antes de filtrar"], answer: 0, explanation: "La proyección permite que EF genere un SELECT con las columnas necesarias y evita exponer directamente la entidad.", clarification: "Proyectar también reduce acoplamiento entre el contrato HTTP y el modelo de persistencia." },
  { prompt: "¿Qué es el problema N+1?", code: "var orders = await db.Orders.ToListAsync();\nforeach (var order in orders)\n    Console.WriteLine(order.Customer.Name);", options: ["Una consulta inicial más muchas consultas adicionales por cada elemento", "Una transacción con N niveles", "Un error exclusivo de migraciones", "Una consulta que siempre usa un índice"], answer: 0, explanation: "N+1 ocurre cuando cargas una colección y luego disparas otra consulta por cada fila o navegación.", clarification: "Busca el problema con logs y métricas; posibles soluciones son proyección, Include controlado o una consulta explícita bien diseñada." },
  { prompt: "¿Para qué sirven las migraciones de EF Core?", code: "dotnet ef migrations add AddStatus\ndotnet ef database update", options: ["Versionar y aplicar cambios del modelo al esquema de la base", "Guardar datos de producción en Git", "Optimizar automáticamente todos los índices", "Reemplazar las pruebas de integración"], answer: 0, explanation: "Las migraciones describen cambios incrementales del esquema y permiten aplicarlos de forma controlada.", clarification: "Una migración no sustituye una estrategia de despliegue: revisa el SQL, el riesgo de bloqueo y el rollback antes de producción." },
  { prompt: "¿Qué garantiza una transacción en este caso?", code: "await using var tx = await db.Database.BeginTransactionAsync();\n// varios cambios\nawait db.SaveChangesAsync();\nawait tx.CommitAsync();", options: ["Que el conjunto de operaciones se confirme o se revierta como unidad", "Que cada consulta sea más rápida", "Que no existan conflictos entre usuarios", "Que EF no genere SQL"], answer: 0, explanation: "Una transacción mantiene la atomicidad del conjunto de operaciones según las reglas de la base de datos.", clarification: "Una transacción no resuelve por sí sola concurrencia, deadlocks o lógica de reintentos; eso requiere diseño adicional." },
  { prompt: "¿Qué problema aborda un token de concurrencia?", code: "public byte[] RowVersion { get; set; }\n// dos usuarios editan el mismo registro", options: ["Detectar que otro proceso modificó la fila antes de guardar", "Encriptar todos los campos", "Evitar cualquier lectura concurrente", "Crear una relación muchos a muchos"], answer: 0, explanation: "La concurrencia optimista detecta cambios mediante una versión o timestamp y evita sobrescribir silenciosamente el trabajo ajeno.", clarification: "Al detectar el conflicto debes decidir: rechazar, combinar, volver a cargar o pedir al usuario que resuelva." },
  { prompt: "¿Qué error de diseño ves al registrar un `DbContext` como singleton?", code: "services.AddSingleton<AppDbContext>();", options: ["Puede compartir estado mutable entre requests y no es seguro para uso concurrente", "Siempre mejora el rendimiento", "Desactiva las migraciones", "Convierte EF en microservicios"], answer: 0, explanation: "DbContext no está diseñado para uso concurrente y su change tracker puede retener estado de requests anteriores.", clarification: "El lifetime típico es scoped. Singleton sería una excepción muy específica y requiere un diseño que no corresponde al contexto normal de una API." },
];

export function EntityFrameworkReview() {
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [completed, setCompleted] = useState<number[]>([]);
  const question = efQuestions[index];
  const done = completed.length === efQuestions.length;

  const answer = (choice: number) => {
    if (selected !== null) return;
    setSelected(choice);
    setCompleted(values => values.includes(index) ? values : [...values, index]);
  };
  const next = () => { setIndex(value => (value + 1) % efQuestions.length); setSelected(null); };
  const reset = () => { setIndex(0); setSelected(null); setCompleted([]); };

  return <section className="ef-review"><div className="ef-review-heading"><div><p className="eyebrow">REPASO .NET</p><h2>Entity Framework Core <span>sin zonas grises.</span></h2><p>Responde, revisa la explicación y aclara la trampa típica de entrevista antes de pasar al siguiente concepto.</p></div><div className="ef-progress-count"><strong>{completed.length}/{efQuestions.length}</strong><span>conceptos revisados</span></div></div><div className="ef-topic-strip"><span>ORM</span><span>LINQ</span><span>DbContext</span><span>tracking</span><span>SQL</span><span>arquitectura</span></div>{done && <div className="ef-complete"><b>✓ Repaso completado</b><span>Vuelve a empezar para consolidar los conceptos con otra vuelta.</span><button onClick={reset}>Repetir repaso</button></div>}<div className="ef-card"><div className="ef-card-meta"><span>{question.area || "EF CORE"}</span><b>Pregunta {index + 1} de {efQuestions.length}</b></div><h3>{question.prompt}</h3><pre>{question.code}</pre><div className="ef-options">{question.options.map((option, optionIndex) => <button key={option} className={`${selected !== null && optionIndex === question.answer ? "correct" : ""} ${selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} onClick={() => answer(optionIndex)} disabled={selected !== null}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{selected !== null && <div className={`ef-feedback ${selected === question.answer ? "good" : "bad"}`}><strong>{selected === question.answer ? "Correcto" : "Repasemos esta idea"}</strong><p>{question.explanation}</p><div><b>Aclaración de entrevista:</b> {question.clarification}</div></div>}</div>{selected !== null && <button className="primary-cta ef-next" onClick={next}>{index === efQuestions.length - 1 ? "Volver al inicio" : "Siguiente aclaración →"}</button>}</section>;
}
