"use client";
import { useState } from "react";
import { allSteps as steps } from "./lessons-all";

export function LessonViewer({lessonId,onClose,onComplete}:{lessonId:string;onClose:()=>void;onComplete:(lessonId:string)=>void}){
 const lesson=steps.find(item=>item.id===lessonId)||steps[0];const [index,setIndex]=useState(0);const [selected,setSelected]=useState<number|null>(null);const [submitted,setSubmitted]=useState(false);const current=lesson.questions[index];const correct=selected===current.answer;const visibleCode=current.code;
 const next=()=>{if(index<lesson.questions.length-1){setIndex(i=>i+1);setSelected(null);setSubmitted(false)}else{onComplete(lesson.id);onClose()}};
 return <section className="lesson-viewer"><button className="back-link" onClick={onClose}>← Volver al path</button><div className="lesson-viewer-head"><div><p className="eyebrow">SINTAXIS ESENCIAL · {index+1} DE {lesson.questions.length}</p><h2>{lesson.title}</h2></div><span className="lesson-status">10 preguntas</span></div><div className="lesson-concept"><p>{lesson.summary}</p><pre><code>{lesson.code}</code></pre></div><div className="lesson-progress"><div style={{width:`${((index+(submitted?1:0))/lesson.questions.length)*100}%`}}/></div><div className="lesson-quiz"><p className="eyebrow">PREGUNTA {index+1}</p><h3>{current.prompt}</h3>{visibleCode&&<pre className="mini-code"><code>{visibleCode}</code></pre>}<div className="lesson-options">{current.options.map((option,i)=><button key={option} className={`lesson-option ${!submitted&&selected===i?"selected":""} ${submitted&&i===current.answer?"right":""} ${submitted&&selected===i&&i!==current.answer?"wrong":""}`} onClick={()=>!submitted&&setSelected(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{submitted&&<div className={`lesson-feedback ${correct?"good":"bad"}`}><strong>{correct?"¡Correcto!":"Repasa este punto."}</strong><p>{current.why}</p></div>}{!submitted?<button className="primary-cta lesson-submit" disabled={selected===null} onClick={()=>setSubmitted(true)}>Comprobar respuesta <span>→</span></button>:correct?<button className="primary-cta lesson-submit" onClick={next}>{index<lesson.questions.length-1?"Siguiente pregunta":"Terminar paso"}<span>→</span></button>:<button className="primary-cta lesson-submit" onClick={()=>{setSubmitted(false);setSelected(null)}}>Intentarlo de nuevo <span>↻</span></button>}</div></section>;
}
