"use client";
import { useEffect, useState, type ChangeEvent } from "react";
import { CurriculumProgress } from "./curriculum-progress";
import { LessonViewer } from "./lesson-viewer";
import { StudyTopics } from "./study-topics";
import { loadProgressFromGoogleSheets, sendToGoogleSheets, type ProgressState } from "./google-sync";

type Lesson={title:string;subtitle:string;icon:string;color:string;progress:number;level:string;topic:string};
type Question={id:string;topic:string;title:string;prompt:string;code:string;options:string[];answer:string;explanation:string};
const topicOrder=["Fundamentos","Tipos","POO","LINQ","Async","Entrevista"];
const defaultSheetsEndpoint="https://script.google.com/macros/s/AKfycbzSAtqnUmDT99WGvtMejdRFqRBszVLzUesa5lkQFfSkQjw_1KTIvp66nnF6EOrMQhJh/exec";
const lessons:Lesson[]=[
 {title:"Fundamentos",subtitle:"Tipos, variables y control de flujo",icon:"⌘",color:"violet",progress:72,level:"Nivel 1",topic:"Fundamentos"},
 {title:"Tipos que confunden",subtitle:"class · struct · record",icon:"◇",color:"peach",progress:35,level:"Nivel 2",topic:"Tipos"},
 {title:"POO en acción",subtitle:"Herencia, interfaces y SOLID",icon:"◎",color:"blue",progress:0,level:"Nivel 3",topic:"POO"},
 {title:"Colecciones + LINQ",subtitle:"Filtrar, proyectar y agrupar",icon:"≋",color:"mint",progress:0,level:"Nivel 4",topic:"LINQ"},
 {title:"Async / await",subtitle:"Tasks, concurrencia y errores",icon:"↯",color:"yellow",progress:0,level:"Nivel 5",topic:"Async"},
 {title:"Entrevista .NET",subtitle:"Retos con tiempo y explicación",icon:"▣",color:"pink",progress:0,level:"Boss final",topic:"Entrevista"},
];
const seedQuestions:Question[]=[
 {id:"types-record",topic:"Tipos",title:"Elige el tipo correcto",prompt:"¿Qué palabra clave usarías para crear un tipo que representa datos inmutables y genera igualdad por valor automáticamente?",code:"public ___ User (string Name);",options:["class","struct","record","interface"],answer:"record",explanation:"Un record modela datos y compara por valor. Una class compara referencias por defecto."},
 {id:"types-value",topic:"Tipos",title:"¿Referencia o valor?",prompt:"¿Cuál de estos es un value type en C#?",code:"___ age = 37;",options:["string","object","int","class"],answer:"int",explanation:"Los tipos numéricos como int son value types. string y object son reference types."},
 {id:"fundamentals-increment",topic:"Fundamentos",title:"Control de flujo",prompt:"¿Qué imprime este código?",code:"int x = 2;\nConsole.WriteLine(x++);",options:["1","2","3","Error"],answer:"2",explanation:"El post-incremento devuelve primero el valor actual y luego incrementa x."},
 {id:"oop-interface",topic:"POO",title:"Contrato de comportamiento",prompt:"¿Qué usarías para definir un contrato que varias clases pueden implementar?",code:"public ___ ILoggable { void Log(); }",options:["record","struct","interface","namespace"],answer:"interface",explanation:"Una interface define un contrato. Una clase puede implementar varias interfaces."},
 {id:"oop-protected",topic:"POO",title:"Encapsulación",prompt:"¿Qué modificador permite acceso desde la clase y sus clases derivadas?",code:"protected string Name;",options:["private","internal","protected","static"],answer:"protected",explanation:"protected permite acceso a la clase que declara el miembro y a sus descendientes."},
 {id:"linq-where",topic:"LINQ",title:"Filtrar colecciones",prompt:"¿Qué método LINQ devuelve solo los elementos que cumplen una condición?",code:"numbers.___(n => n > 10);",options:["Select","Where","OrderBy","First"],answer:"Where",explanation:"Where filtra. Select transforma cada elemento y OrderBy ordena la secuencia."},
 {id:"async-task",topic:"Async",title:"Trabajo asíncrono",prompt:"¿Qué devuelve normalmente un método async que produce un resultado?",code:"async ___ GetUserAsync()",options:["void","Task<User>","Thread<User>","Promise<User>"],answer:"Task<User>",explanation:"En .NET se usa Task<T> para representar una operación asíncrona que producirá un valor."},
 {id:"solid-dip",topic:"Entrevista",title:"Buenas prácticas",prompt:"¿Qué principio SOLID recomienda depender de abstracciones?",code:"D = ___",options:["Data principle","Dependency Inversion","Dynamic Inheritance","Default Interface"],answer:"Dependency Inversion",explanation:"Dependency Inversion Principle: los módulos de alto nivel no deben depender de detalles concretos."},
];
const extraQuestions:Question[]=[
 {id:"types-int",topic:"Tipos",title:"Tipos integrados",prompt:"¿Qué tipo representa un entero con signo de 32 bits?",code:"___ count = 10;",options:["int","long","double","byte"],answer:"int",explanation:"int es un entero con signo de 32 bits. long usa 64 bits y byte almacena 0 a 255."},
 {id:"types-long",topic:"Tipos",title:"Tipos integrados",prompt:"¿Qué sufijo indica que un literal entero debe tratarse como long?",code:"var distance = 384_400_000___;",options:["L","D","M","I"],answer:"L",explanation:"El sufijo L indica un literal long. D es para double y M para decimal."},
 {id:"types-double",topic:"Tipos",title:"Tipos integrados",prompt:"Sin sufijo, ¿qué tipo tiene normalmente 3.14?",code:"var value = 3.14;",options:["float","double","decimal","int"],answer:"double",explanation:"Un literal con punto decimal es double por defecto. float usa f y decimal usa m."},
 {id:"types-decimal",topic:"Tipos",title:"Tipos integrados",prompt:"¿Qué literal es de tipo decimal?",code:"var price = 19.99___;",options:["d","f","m","c"],answer:"m",explanation:"El sufijo m indica decimal, apropiado para precisión monetaria."},
 {id:"types-bool",topic:"Tipos",title:"Tipos integrados",prompt:"¿Cuál es el único valor válido para un bool además de true?",code:"bool ready = ___;",options:["1","yes","false","null"],answer:"false",explanation:"bool solo tiene true o false; no es convertible implícitamente desde int."},
 {id:"types-char",topic:"Tipos",title:"Tipos integrados",prompt:"¿Cuál declara correctamente un solo carácter?",code:"char initial = ___;",options:["\"A\"","'A'","A","`A`"],answer:"'A'",explanation:"char usa comillas simples. string usa comillas dobles."},
 {id:"types-string",topic:"Tipos",title:"Tipos integrados",prompt:"¿Cuál afirmación sobre string es correcta?",code:"string name = \"Ada\";",options:["Es un value type","Es mutable en sitio","Es un reference type e inmutable","Solo acepta ASCII"],answer:"Es un reference type e inmutable",explanation:"string es reference type, pero sus operaciones producen nuevas cadenas porque su contenido es inmutable."},
 {id:"types-default",topic:"Tipos",title:"Valores predeterminados",prompt:"¿Qué valor produce default para int?",code:"int value = default;",options:["null","false","0","-1"],answer:"0",explanation:"El valor predeterminado de int es 0; el de bool es false y el de referencias es null."},
 {id:"fund-var",topic:"Fundamentos",title:"Variables",prompt:"¿Cuál línea no compila?",code:"var a = 10;\n___ b;",options:["int","string","var","double"],answer:"var",explanation:"var necesita un inicializador para que el compilador pueda inferir el tipo."},
 {id:"fund-const",topic:"Fundamentos",title:"Constantes",prompt:"¿Qué palabra clave impide reasignar un valor después de inicializarlo?",code:"___ int Max = 10;",options:["readonly","const","static","fixed"],answer:"const",explanation:"const declara una constante evaluada en compilación. readonly se asigna en declaración o constructor."},
 {id:"fund-cast",topic:"Fundamentos",title:"Conversiones",prompt:"¿Qué ocurre con esta conversión explícita?",code:"int n = (int)3.9;",options:["n vale 3","n vale 4","Error siempre","n vale 3.9"],answer:"n vale 3",explanation:"El cast a int descarta la parte decimal; no redondea."},
 {id:"fund-parse",topic:"Fundamentos",title:"Conversiones",prompt:"¿Qué opción es más segura para texto que podría no ser numérico?",code:"int.TryParse(input, out var number);",options:["Parse","TryParse","Cast","ConvertOnly"],answer:"TryParse",explanation:"TryParse indica éxito o fallo con bool sin lanzar una excepción por formato inválido."},
 {id:"fund-precedence",topic:"Fundamentos",title:"Operadores",prompt:"¿Qué imprime?",code:"Console.WriteLine(2 + 3 * 4);",options:["20","14","24","Error"],answer:"14",explanation:"La multiplicación tiene precedencia sobre la suma: 2 + (3 * 4)."},
 {id:"fund-increment",topic:"Fundamentos",title:"Operadores",prompt:"¿Qué imprime?",code:"int x = 2;\nConsole.WriteLine(++x);",options:["1","2","3","Error"],answer:"3",explanation:"El pre-incremento aumenta x antes de evaluar la expresión."},
 {id:"fund-null",topic:"Fundamentos",title:"Null",prompt:"¿Qué operador devuelve el valor de la derecha solo si name es null?",code:"var label = name ___ \"Unknown\";",options:["??","?.","!","::"],answer:"??",explanation:"El operador null-coalescing ?? usa el operando derecho cuando el izquierdo es null."},
 {id:"fund-ternary",topic:"Fundamentos",title:"Operadores",prompt:"¿Qué operador representa una condición inline?",code:"var text = ok ___ \"yes\" : \"no\";",options:["??","?.","?","=>"],answer:"?",explanation:"El operador condicional usa la forma condición ? valorSiTrue : valorSiFalse."},
 {id:"fund-utc",topic:"Fundamentos",title:"DateTime",prompt:"¿Qué conviene usar para un timestamp independiente de zona horaria?",code:"var created = DateTime.___;",options:["Now","UtcNow","Local","Universal"],answer:"UtcNow",explanation:"UtcNow produce el instante en UTC, útil para persistencia y comunicación entre sistemas."},
 {id:"fund-interp",topic:"Fundamentos",title:"Strings",prompt:"¿Qué prefijo activa interpolación?",code:"___\"Total: {total}\"",options:["$","@","#","&"],answer:"$",explanation:"El prefijo $ permite insertar expresiones entre llaves en una cadena."},
 {id:"oop-class",topic:"POO",title:"Clases",prompt:"¿Qué palabra clave crea una instancia de una clase?",code:"var user = ___ User();",options:["make","new","create","instance"],answer:"new",explanation:"new reserva y construye una instancia llamando a un constructor."},
 {id:"oop-private",topic:"POO",title:"Encapsulación",prompt:"¿Cuál es la accesibilidad predeterminada de un miembro de clase?",code:"class User { string name; }",options:["public","protected","private","internal"],answer:"private",explanation:"Los miembros de una clase son private por defecto; los tipos top-level son internal por defecto."},
 {id:"oop-abstract",topic:"POO",title:"Abstracción",prompt:"¿Puede instanciarse directamente una clase abstracta?",code:"var service = new AbstractService();",options:["Sí, siempre","No","Solo con var","Solo si es static"],answer:"No",explanation:"Una clase abstracta sirve como base y no puede instanciarse directamente."},
 {id:"oop-override",topic:"POO",title:"Polimorfismo",prompt:"¿Qué palabra clave reemplaza la implementación virtual heredada?",code:"public ___ void Run()",options:["overload","override","replace","virtual"],answer:"override",explanation:"override proporciona la implementación específica en la clase derivada."},
 {id:"oop-sealed",topic:"POO",title:"Herencia",prompt:"¿Qué impide que una clase sea heredada?",code:"public ___ class Token {}",options:["closed","final","sealed","static"],answer:"sealed",explanation:"sealed evita que otras clases deriven de esa clase."},
 {id:"oop-interface-multi",topic:"POO",title:"Interfaces",prompt:"¿Cuántas interfaces puede implementar una clase?",code:"class Report : IPrintable, IExportable {}",options:["Una","Dos como máximo","Cualquier cantidad razonable","Ninguna"],answer:"Cualquier cantidad razonable",explanation:"Una clase puede implementar múltiples interfaces, aunque solo puede heredar de una clase base."},
 {id:"oop-composition",topic:"POO",title:"Diseño",prompt:"¿Qué relación representa mejor composition?",code:"class Car { private Engine engine; }",options:["Tiene-un","Es-un","Compila-un","Hereda-de"],answer:"Tiene-un",explanation:"Car tiene un Engine: composition modela colaboración y pertenencia, no herencia."},
 {id:"oop-record-eq",topic:"POO",title:"Records",prompt:"¿Cómo comparan por defecto dos record class con los mismos datos?",code:"new User(1) == new User(1)",options:["Por referencia","Por valor","Nunca compilan","Solo si son struct"],answer:"Por valor",explanation:"Los records generan igualdad basada en valores; las clases ordinarias usan igualdad por referencia por defecto."},
 {id:"oop-property",topic:"POO",title:"Propiedades",prompt:"¿Qué permite esta propiedad?",code:"public string Name { get; private set; }",options:["Cualquiera puede escribirla","Solo la clase puede asignarla","Es constante","Es static"],answer:"Solo la clase puede asignarla",explanation:"El setter privado restringe la modificación desde fuera del tipo."},
 {id:"linq-select",topic:"LINQ",title:"Transformar colecciones",prompt:"¿Qué método transforma cada elemento?",code:"names.___(n => n.Length);",options:["Where","Select","Filter","MapOnly"],answer:"Select",explanation:"Select proyecta cada elemento hacia una nueva forma o valor."},
 {id:"linq-any",topic:"LINQ",title:"Consultar colecciones",prompt:"¿Qué método pregunta si existe al menos un elemento que cumple?",code:"items.___(x => x.Active);",options:["Any","All","ExistsOnly","ContainsPredicate"],answer:"Any",explanation:"Any devuelve true si al menos un elemento cumple la condición."},
 {id:"linq-all",topic:"LINQ",title:"Consultar colecciones",prompt:"¿Qué método exige que todos cumplan?",code:"items.___(x => x.IsValid);",options:["Any","All","Every","Where"],answer:"All",explanation:"All devuelve true solo cuando todos los elementos satisfacen el predicado."},
 {id:"linq-first",topic:"LINQ",title:"Elementos",prompt:"¿Qué diferencia clave existe entre First y FirstOrDefault?",code:"items.FirstOrDefault();",options:["El segundo no lanza por secuencia vacía","First siempre devuelve null","No hay diferencia","FirstOrDefault solo sirve para int"],answer:"El segundo no lanza por secuencia vacía",explanation:"First lanza si no hay elementos; FirstOrDefault devuelve el valor por defecto."},
 {id:"linq-order",topic:"LINQ",title:"Ordenar",prompt:"¿Qué método ordena ascendentemente por una clave?",code:"items.___(x => x.Name);",options:["SortBy","OrderBy","Arrange","SequenceBy"],answer:"OrderBy",explanation:"OrderBy inicia una ordenación ascendente; ThenBy agrega criterios secundarios."},
 {id:"linq-deferred",topic:"LINQ",title:"Ejecución diferida",prompt:"¿Cuándo se ejecuta normalmente una consulta LINQ diferida?",code:"var query = items.Where(x => x.Active);",options:["Al declarar query","Al enumerarla","Al compilar la app","Nunca"],answer:"Al enumerarla",explanation:"Muchas operaciones LINQ usan ejecución diferida y se evalúan al enumerar, por ejemplo con foreach."},
 {id:"linq-group",topic:"LINQ",title:"Agrupar",prompt:"¿Qué método crea grupos por una clave?",code:"orders.___(o => o.CustomerId);",options:["ClusterBy","GroupBy","Partition","Bucket"],answer:"GroupBy",explanation:"GroupBy reúne elementos en grupos que comparten la misma clave."},
 {id:"linq-query",topic:"LINQ",title:"LINQ",prompt:"¿Qué interfaz representa una secuencia que puede enumerarse?",code:"IEnumerable<int> values = ...;",options:["IQueryableOnly","IEnumerable<T>","ISequence<T>","IListRequired"],answer:"IEnumerable<T>",explanation:"IEnumerable<T> representa una secuencia enumerable y es la base de muchas operaciones LINQ."},
 {id:"linq-side",topic:"LINQ",title:"Buenas prácticas",prompt:"¿Qué riesgo tiene modificar una colección mientras la enumeras?",code:"foreach (var x in items) items.Remove(x);",options:["Ninguno","InvalidOperationException","Siempre duplica","Convierte a array"],answer:"InvalidOperationException",explanation:"Modificar la colección durante la enumeración suele invalidar el enumerador."},
 {id:"async-void",topic:"Async",title:"Async",prompt:"¿Cuál es el retorno recomendado para un método async sin resultado?",code:"async ___ SaveAsync()",options:["void","Task","Thread","Promise"],answer:"Task",explanation:"Task permite esperar y observar errores. async void se reserva casi exclusivamente para event handlers."},
 {id:"async-await",topic:"Async",title:"Await",prompt:"¿Qué hace await?",code:"var user = await GetUserAsync();",options:["Bloquea siempre un thread","Espera la Task sin bloquear de esa forma el flujo async","Crea un thread nuevo siempre","Convierte a sync"],answer:"Espera la Task sin bloquear de esa forma el flujo async",explanation:"await suspende el método async hasta que la Task termina y permite que el contexto continúe."},
 {id:"async-all",topic:"Async",title:"Concurrencia",prompt:"¿Qué combina varias tareas y espera a que todas terminen?",code:"await Task.___(tasks);",options:["JoinAll","WhenAll","ParallelAll","WaitMany"],answer:"WhenAll",explanation:"Task.WhenAll completa cuando todas las tareas proporcionadas terminan."},
 {id:"async-cancel",topic:"Async",title:"Cancelación",prompt:"¿Qué se pasa a una API async para solicitar cancelación cooperativa?",code:"GetDataAsync(___ token)",options:["CancellationToken","CancelFlag","AbortHandle","StopThread"],answer:"CancellationToken",explanation:"CancellationToken comunica una solicitud de cancelación; el código debe observarla y cooperar."},
 {id:"async-exception",topic:"Async",title:"Errores",prompt:"¿Dónde se captura normalmente una excepción de una Task esperada?",code:"try { await WorkAsync(); } catch { }",options:["En try/catch alrededor del await","Nunca","Solo en finalizer","En el garbage collector"],answer:"En try/catch alrededor del await",explanation:"Al hacer await, una excepción de la Task se propaga y puede manejarse con try/catch."},
 {id:"async-sequential",topic:"Async",title:"Concurrencia",prompt:"¿Qué opción ejecuta dos tareas de forma concurrente antes de esperar?",code:"var a = A(); var b = B(); await Task.WhenAll(a,b);",options:["La mostrada","await A(); await B();","Thread.Start siempre","No es posible"],answer:"La mostrada",explanation:"Iniciar ambas Tasks antes de esperar permite que su trabajo se solape cuando es apropiado."},
 {id:"async-configure",topic:"Async",title:"Async avanzado",prompt:"¿Cuál afirmación es correcta sobre ConfigureAwait(false)?",code:"await operation.ConfigureAwait(false);",options:["Desactiva la Task","No captura el contexto de sincronización","Convierte a thread pool siempre","Cancela la operación"],answer:"No captura el contexto de sincronización",explanation:"ConfigureAwait(false) evita solicitar volver al contexto capturado; no cancela ni elimina la asincronía."},
 {id:"async-deadlock",topic:"Async",title:"Trampa de entrevistas",prompt:"¿Por qué bloquear con .Result puede ser peligroso?",code:"var result = GetAsync().Result;",options:["Puede causar deadlocks y bloquear threads","Siempre es más rápido","Convierte a value type","No compila nunca"],answer:"Puede causar deadlocks y bloquear threads",explanation:"Bloquear una operación async puede bloquear el contexto y consumir threads innecesariamente."},
 {id:"async-task-return",topic:"Async",title:"Tipos de retorno",prompt:"¿Qué tipo representa una operación que devolverá un User?",code:"async ___ GetUserAsync()",options:["Task<User>","UserTask","Promise<User>","Thread<User>"],answer:"Task<User>",explanation:"Task<T> representa una operación asíncrona que producirá un resultado de tipo T."},
 {id:"interview-solid",topic:"Entrevista",title:"SOLID",prompt:"¿Qué principio dice que una clase debe tener una razón para cambiar?",code:"S = ___",options:["Single Responsibility","Static Reference","Safe Runtime","Service Routing"],answer:"Single Responsibility",explanation:"SRP busca una sola razón principal para cambiar, manteniendo responsabilidades cohesionadas."},
 {id:"interview-open",topic:"Entrevista",title:"SOLID",prompt:"¿Qué principio favorece extender sin modificar código estable?",code:"O = ___",options:["Open/Closed","Object Copy","Override Only","Output"],answer:"Open/Closed",explanation:"Open/Closed: abierto a extensión, cerrado a modificación."},
 {id:"interview-liskov",topic:"Entrevista",title:"SOLID",prompt:"¿Qué principio trata la sustitución segura de subtipos?",code:"L = ___",options:["Liskov Substitution","Local State","Layered Service","List Safety"],answer:"Liskov Substitution",explanation:"Los subtipos deben poder sustituir a sus tipos base sin romper las expectativas del programa."},
 {id:"interview-dependency",topic:"Entrevista",title:"SOLID",prompt:"¿Qué técnica reduce el acoplamiento al recibir dependencias desde fuera?",code:"class Service(IRepository repo) {}",options:["Dependency Injection","Global state","Static access","Deep inheritance"],answer:"Dependency Injection",explanation:"La inyección de dependencias entrega colaboraciones desde fuera y facilita pruebas y reemplazos."},
 {id:"interview-generic",topic:"Entrevista",title:"Generics",prompt:"¿Cuál es una ventaja de List<T>?",code:"List<int> values = new();",options:["Tipado en compilación y reutilización","Solo acepta strings","Evita toda asignación","Convierte todo a object"],answer:"Tipado en compilación y reutilización",explanation:"Los genéricos permiten reutilizar el código manteniendo seguridad de tipos."},
 {id:"interview-boxing",topic:"Entrevista",title:"Memoria",prompt:"¿Qué es boxing?",code:"object value = 42;",options:["Copiar un value type dentro de object","Crear una clase abstracta","Ordenar una lista","Convertir string a int"],answer:"Copiar un value type dentro de object",explanation:"Boxing envuelve un value type en un objeto; unboxing requiere una conversión compatible."},
 {id:"interview-dispose",topic:"Entrevista",title:"Recursos",prompt:"¿Qué patrón ayuda a liberar recursos no administrados?",code:"using var connection = new Connection();",options:["IDisposable/using","final static","GC.Collect siempre","readonly"],answer:"IDisposable/using",explanation:"IDisposable expresa liberación determinista y using garantiza Dispose al salir del alcance."},
 {id:"interview-nullable",topic:"Entrevista",title:"Nullability",prompt:"¿Qué indica string? en nullable reference types?",code:"string? name = null;",options:["Puede ser null","Nunca puede ser null","Es value type","Es dynamic"],answer:"Puede ser null",explanation:"El ? expresa que una referencia puede ser null y permite al compilador advertir usos inseguros."},
 {id:"interview-equality",topic:"Entrevista",title:"Igualdad",prompt:"¿Qué diferencia suele existir entre == en una class y en un record?",code:"new User(1) == new User(1)",options:["class referencia; record valor","class valor; record referencia","Ambos siempre referencia","Ambos siempre valor"],answer:"class referencia; record valor",explanation:"Una class usa igualdad por referencia por defecto; un record genera igualdad basada en valores."},
];
const questions:Question[]=[...seedQuestions,...extraQuestions];

export default function Home(){
 const [tab,setTab]=useState("Ruta"),[selected,setSelected]=useState<string|null>(null),[answered,setAnswered]=useState(false),[xp,setXp]=useState(1240),[streak,setStreak]=useState(7),[topic,setTopic]=useState("Todos"),[completed,setCompleted]=useState(0),[correct,setCorrect]=useState(0),[ready,setReady]=useState(false),[cloudLoaded,setCloudLoaded]=useState(false),[saveNotice,setSaveNotice]=useState(""),[planIds,setPlanIds]=useState<string[]>(questions.map(q=>q.id)),[planIndex,setPlanIndex]=useState(0),[mastered,setMastered]=useState<Record<string,string[]>>({}),[moduleDone,setModuleDone]=useState(false),[lessonId,setLessonId]=useState<string|null>(null),[completedSteps,setCompletedSteps]=useState<string[]>([]),[sheetsEndpoint,setSheetsEndpoint]=useState(defaultSheetsEndpoint),[sheetsNotice,setSheetsNotice]=useState("");
 const available=topic==="Todos"?questions:questions.filter(q=>q.topic===topic);
 const currentId=planIds[planIndex]||available[0]?.id||questions[0].id;
 const question=questions.find(q=>q.id===currentId)||questions[0];
 const topicQuestions=questions.filter(q=>q.topic===question.topic);
 const masteredIds=mastered[question.topic]||[];
 const nextTopicName=topicOrder[topicOrder.indexOf(question.topic)+1];
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const raw=localStorage.getItem("csharp-quest-progress-v1");if(raw){const saved=JSON.parse(raw);if(typeof saved.xp==="number")setXp(saved.xp);if(typeof saved.streak==="number")setStreak(saved.streak);if(typeof saved.completed==="number")setCompleted(saved.completed);if(typeof saved.correct==="number")setCorrect(saved.correct);if(typeof saved.topic==="string")setTopic(saved.topic);if(Array.isArray(saved.planIds))setPlanIds(saved.planIds);if(typeof saved.planIndex==="number")setPlanIndex(saved.planIndex);if(saved.mastered&&typeof saved.mastered==="object")setMastered(saved.mastered);if(saved.moduleDone===true)setModuleDone(true);if(Array.isArray(saved.completedSteps))setCompletedSteps(saved.completedSteps);if(typeof saved.sheetsEndpoint==="string"&&saved.sheetsEndpoint.trim())setSheetsEndpoint(saved.sheetsEndpoint)}}catch{}setReady(true)},[]);
 useEffect(()=>{if(!ready||!cloudLoaded)return;try{localStorage.setItem("csharp-quest-progress-v1",JSON.stringify({version:4,xp,streak,completed,correct,topic,planIds,planIndex,mastered,moduleDone,completedSteps,sheetsEndpoint,updatedAt:new Date().toISOString()}))}catch{}},[ready,cloudLoaded,xp,streak,completed,correct,topic,planIds,planIndex,mastered,moduleDone,completedSteps,sheetsEndpoint]);
 const currentProgress=():ProgressState=>({version:4,xp,streak,completed,correct,topic,planIds,planIndex,mastered,moduleDone,completedSteps,updatedAt:new Date().toISOString()});
 const applyProgress=(data:Partial<ProgressState>)=>{if(typeof data.xp==="number")setXp(data.xp);if(typeof data.streak==="number")setStreak(data.streak);if(typeof data.completed==="number")setCompleted(data.completed);if(typeof data.correct==="number")setCorrect(data.correct);if(typeof data.topic==="string")setTopic(data.topic);if(Array.isArray(data.planIds))setPlanIds(data.planIds);if(typeof data.planIndex==="number")setPlanIndex(data.planIndex);if(data.mastered&&typeof data.mastered==="object")setMastered(data.mastered);if(typeof data.moduleDone==="boolean")setModuleDone(data.moduleDone);if(Array.isArray(data.completedSteps))setCompletedSteps(data.completedSteps);setSelected(null);setAnswered(false)};
 useEffect(()=>{if(!ready)return;let cancelled=false;void loadProgressFromGoogleSheets(sheetsEndpoint).then(data=>{if(cancelled)return;if(data){applyProgress(data);setSheetsNotice("Progreso cargado desde Google Sheets.");window.setTimeout(()=>setSheetsNotice(""),4000)}setCloudLoaded(true)});return()=>{cancelled=true}},[ready,sheetsEndpoint]);
 useEffect(()=>{if(!ready||!cloudLoaded||!sheetsEndpoint)return;const timer=window.setTimeout(()=>{void sendToGoogleSheets(sheetsEndpoint,{type:"progreso",progress:currentProgress()}).then(ok=>{if(ok){setSheetsNotice("Progreso sincronizado en Google Sheets.");window.setTimeout(()=>setSheetsNotice(""),3000)}})},800);return()=>window.clearTimeout(timer)},[ready,cloudLoaded,xp,streak,completed,correct,topic,planIds,planIndex,mastered,moduleDone,completedSteps,sheetsEndpoint]);
 const loadCloudProgress=async()=>{setSheetsNotice("Cargando progreso...");const data=await loadProgressFromGoogleSheets(sheetsEndpoint);if(data){applyProgress(data);setSheetsNotice("Progreso cargado desde Google Sheets.")}else setSheetsNotice("No encontré un progreso guardado en esa hoja.");window.setTimeout(()=>setSheetsNotice(""),4000)};
 const exportProgress=()=>{const data={app:"csharp-quest",version:3,savedAt:new Date().toISOString(),xp,streak,completed,correct,topic,planIds,planIndex,mastered,moduleDone,completedSteps};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`csharp-quest-progreso-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setSaveNotice("Archivo preparado: guárdalo en Archivos › iCloud Drive.");setTimeout(()=>setSaveNotice(""),5000)};
 const importProgress=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=="csharp-quest"||(data.version!==1&&data.version!==2&&data.version!==3))throw new Error("invalid");if(typeof data.xp!=="number"||typeof data.streak!=="number")throw new Error("invalid");setXp(data.xp);setStreak(data.streak);setCompleted(data.completed||0);setCorrect(data.correct||0);if(typeof data.topic==="string")setTopic(data.topic);if(Array.isArray(data.planIds))setPlanIds(data.planIds);if(typeof data.planIndex==="number")setPlanIndex(data.planIndex);if(data.mastered&&typeof data.mastered==="object")setMastered(data.mastered);if(Array.isArray(data.completedSteps))setCompletedSteps(data.completedSteps);setModuleDone(data.moduleDone===true);setSelected(null);setAnswered(false);setSaveNotice("¡Progreso restaurado correctamente!")}catch{setSaveNotice("No pude leer ese archivo de progreso.")}event.target.value="";setTimeout(()=>setSaveNotice(""),5000)};
 const openTopic=(nextTopic:string)=>{const ids=(nextTopic==="Todos"?questions:questions.filter(q=>q.topic===nextTopic)).map(q=>q.id);setTopic(nextTopic);setPlanIds(ids);setPlanIndex(0);setSelected(null);setAnswered(false);setModuleDone(false);setTab("Practicar")};
 const answer=(choice:string)=>{if(answered||moduleDone)return;setSelected(choice);setAnswered(true);setCompleted(v=>v+1);const isCorrect=choice===question.answer;void sendToGoogleSheets(sheetsEndpoint,{type:"respuesta",topic:question.topic,question:question.prompt,answer:choice,correct:isCorrect,xp:isCorrect?15:0});if(isCorrect){setXp(v=>v+15);setCorrect(v=>v+1);setStreak(v=>Math.max(v,8));const nextMastered={...mastered,[question.topic]:Array.from(new Set([...(mastered[question.topic]||[]),question.id]))};setMastered(nextMastered);const rest=planIds.slice(planIndex+1);const done=rest.length===0&&topicQuestions.every(q=>nextMastered[question.topic]?.includes(q.id));if(done)setModuleDone(true)}else{const other=topicQuestions.find(q=>q.id!==question.id)?.id||question.id;setPlanIds(ids=>[...ids,question.id,other])}};
 const next=()=>{setPlanIndex(v=>v+1);setSelected(null);setAnswered(false)};
 const continueModule=()=>{if(nextTopicName)openTopic(nextTopicName);else{setModuleDone(false);setSaveNotice("¡Completaste toda la ruta disponible!");setTimeout(()=>setSaveNotice(""),5000)}};
 return <main className="app-shell"><div className="grain"/>
  <header className="topbar"><div className="brand"><span className="brand-mark">{`{ }`}</span><span>C# <em>Quest</em></span></div><div className="top-actions"><span className="streak">🔥 {streak}</span><span className="xp">✦ {xp.toLocaleString("en-US")} XP</span><button className="avatar" aria-label="Perfil">V</button></div></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">MI RUTA DE ENTREVISTA</p><h1>Un poco de código.<br/><span>Cada día.</span></h1><p className="hero-text">Domina C# y .NET con retos de 5 minutos, feedback inmediato y práctica que sí se parece a una entrevista.</p><button className="primary-cta" onClick={()=>openTopic("Todos")}>Continuar ruta <span>→</span></button></div><div className="hero-orbit" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="code-orb"><span>c#</span><small>.NET</small></div><div className="float-tag tag-one">POO</div><div className="float-tag tag-two">LINQ</div><div className="float-tag tag-three">async</div></div></section>
  <nav className="tabs" aria-label="Navegación principal">{["Ruta","Temas","Repaso"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t==="Temas"?"⌕ Temas":t}</button>)}</nav>
  {tab==="Temas"&&<StudyTopics/>}
  {tab==="Ruta"&&<>{lessonId?<LessonViewer lessonId={lessonId} onClose={()=>setLessonId(null)} onComplete={(id)=>setCompletedSteps(values=>values.includes(id)?values:[...values,id])}/>:<CurriculumProgress completedSteps={completedSteps} onOpenModule={openTopic} onOpenLesson={setLessonId}/>}</>} 
  {tab==="Ruta"&&<><section className="section-heading"><div><p className="eyebrow">PROGRESO DEL CAMINO</p><h2>Sube de nivel, <span>sin saltos.</span></h2></div><div className="level-pill">Dominio por conceptos</div></section><div className="progress-line"><div style={{width:`${Math.min(100,(correct/Math.max(1,questions.length))*100)}%`}}/></div><section className="lesson-grid">{lessons.map(l=>{const total=questions.filter(q=>q.topic===l.topic).length;const done=(mastered[l.topic]||[]).filter(id=>questions.some(q=>q.topic===l.topic&&q.id===id)).length;return <button className="lesson-card" key={l.title} onClick={()=>openTopic(l.topic)}><div className={`lesson-icon ${l.color}`}>{l.icon}</div><div className="lesson-info"><div className="lesson-meta"><span>{l.level}</span><b>{done===total&&total>0?"Dominado":done>0?`${done}/${total}`:"Disponible"}</b></div><h3>{l.title}</h3><p>{l.subtitle}</p><div className="mini-progress"><div style={{width:`${total?done/total*100:0}%`}}/></div></div><span className="lesson-arrow">→</span></button>})}</section></>}
  {tab==="Practicar"&&<section className="practice-view"><div className="practice-head"><div><p className="eyebrow">{question.topic.toUpperCase()} · +15 XP</p><h2>{question.title}</h2></div><span className="question-count">{Math.min(planIndex+1,planIds.length)} / {planIds.length}</span></div><div className="topic-picker"><button className={topic==="Todos"?"selected-topic":""} onClick={()=>openTopic("Todos")}>Todos</button>{topicOrder.map(t=><button key={t} className={topic===t?"selected-topic":""} onClick={()=>openTopic(t)}>{t}</button>)}</div>{moduleDone?<div className="module-success"><div className="success-mark">✓</div><p className="eyebrow">MÓDULO SUPERADO</p><h2>¡Concepto entendido!</h2><p>Respondiste correctamente todo el módulo <b>{question.topic}</b>. Ya puedes continuar con el siguiente nivel.</p><button className="primary-cta" onClick={continueModule}>{nextTopicName?`Continuar a ${nextTopicName}`:"Ver ruta completada"}<span>→</span></button></div>:<><div className="mastery-line"><span>Dominio: {masteredIds.length}/{topicQuestions.length}</span><span>{planIds.length>topicQuestions.length?"Incluye repaso reforzado":"Primera vuelta"}</span></div><div className="question-card"><p className="question-label">{question.prompt}</p><div className="code-snippet">{question.code.split("\n").map((line,i)=><span key={i}><span className="syntax">{line.split(" ")[0]}</span>{line.substring(line.indexOf(" "))}{i<question.code.split("\n").length-1&&<br/>}</span>)}</div><div className="options">{question.options.map((o,i)=><button key={o} className={`option ${selected===o&&!answered?"selected-option":""} ${answered&&selected===o?(o===question.answer?"correct":"wrong"):""} ${answered&&o===question.answer?"correct-answer":""}`} onClick={()=>answer(o)}><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{o}</span>{answered&&o===question.answer&&<span className="result">✓</span>}{selected===o&&o!==question.answer&&<span className="result">×</span>}</button>)}</div>{answered&&<div className={`feedback ${selected===question.answer?"good":"bad"}`}><strong>{selected===question.answer?"¡Muy bien!":"Necesita repaso."}</strong><span>{selected===question.answer?question.explanation:`Vamos a repetir este concepto y agregar otra pregunta similar. ${question.explanation}`}</span></div>}</div>{answered&&<button className="primary-cta next-button" onClick={next}>Siguiente reto <span>→</span></button>}</>}</section>}
  {tab==="Repaso"&&<section className="review-view"><p className="eyebrow">REPASO INTELIGENTE</p><h2>Lo que conviene <span>volver a mirar.</span></h2><div className="review-card"><div className="review-icon">◌</div><div><h3>class vs struct vs record</h3><p>Conceptos para reforzar · hasta dominarlos</p></div><button onClick={()=>openTopic("Tipos")}>Repasar →</button></div><div className="review-card"><div className="review-icon">⌁</div><div><h3>LINQ y async/await</h3><p>Preguntas prácticas con refuerzo</p></div><button onClick={()=>openTopic("LINQ")}>Empezar →</button></div></section>}
  <section className="backup-box"><div><p className="eyebrow">COPIA DE SEGURIDAD</p><h3>Guarda tu progreso en iCloud Drive</h3><p>Descarga un archivo y vuelve a subirlo cuando quieras restaurar tus datos.</p></div><div className="backup-actions"><button onClick={exportProgress}>↓ Descargar progreso</button><label htmlFor="progress-file">↑ Cargar progreso</label><input id="progress-file" type="file" accept=".json,application/json" onChange={importProgress}/></div></section><section className="sheets-box"><div><p className="eyebrow">SINCRONIZACIÓN</p><h3>Google Sheets</h3><p>Conecta una hoja para guardar cada respuesta desde cualquier lugar.</p></div><div className="sheets-config"><input value={sheetsEndpoint} onChange={e=>setSheetsEndpoint(e.target.value)} placeholder="Pega aquí la URL del Apps Script" aria-label="URL de Google Apps Script"/><button onClick={()=>{localStorage.setItem("csharp-quest-progress-v1",JSON.stringify({version:4,xp,streak,completed,correct,topic,planIds,planIndex,mastered,moduleDone,completedSteps,sheetsEndpoint,updatedAt:new Date().toISOString()}));setSheetsNotice(sheetsEndpoint?"URL guardada. Las próximas respuestas se sincronizarán.":"Pega primero la URL del Apps Script.");setTimeout(()=>setSheetsNotice(""),5000)}}>Guardar conexión</button></div></section>{sheetsNotice&&<p className="save-notice">{sheetsNotice}</p>}{saveNotice&&<p className="save-notice">{saveNotice}</p>}
  <footer><span>✓ Progreso local · {correct}/{completed} respuestas correctas</span><span>Racha actual: <b>{streak} días</b></span></footer>
 </main>;
}
