"use client";

import { useState } from "react";

type SqlQuestion = { prompt: string; code: string; options: string[]; answer: number; explanation: string; interview: string };

const selectQuestions: SqlQuestion[] = [
  { prompt: "¿Qué consulta devuelve el nombre de cada cliente?", code: "___ FirstName\nFROM Sales.Customer;", options: ["SELECT", "GET", "READ", "SHOW"], answer: 0, explanation: "SELECT indica las columnas que quieres devolver.", interview: "Explica la estructura mínima de una consulta SELECT." },
  { prompt: "¿Qué cláusula indica de qué tabla vienen los datos?", code: "SELECT FirstName\n___ Sales.Customer;", options: ["IN", "FROM", "TABLE", "SOURCE"], answer: 1, explanation: "FROM especifica la tabla o conjunto de tablas de origen.", interview: "¿Qué diferencia hay entre SELECT y FROM?" },
  { prompt: "¿Cómo seleccionarías todas las columnas de Customer?", code: "SELECT ___\nFROM Sales.Customer;", options: ["ALL", "COLUMNS", "*", "EVERY"], answer: 2, explanation: "El asterisco representa todas las columnas, aunque conviene evitarlo cuando no necesitas todas.", interview: "¿Por qué puede ser mala idea usar SELECT * en producción?" },
  { prompt: "¿Cómo cambiarías el nombre de una columna en el resultado?", code: "SELECT FirstName ___ Nombre\nFROM Sales.Customer;", options: ["RENAME", "AS", "TO", "ALIAS"], answer: 1, explanation: "AS crea un alias para mostrar un nombre más claro en el resultado.", interview: "¿Un alias cambia la columna en la tabla? No, solo el nombre del resultado." },
  { prompt: "¿Qué expresión crea FullName uniendo nombre y apellido?", code: "SELECT FirstName + ' ' + ___ AS FullName\nFROM Sales.Customer;", options: ["Name", "Surname", "LastName", "CustomerName"], answer: 2, explanation: "El operador + concatena valores de texto fila por fila.", interview: "¿Qué debes considerar si FirstName o LastName contiene NULL?" },
  { prompt: "¿Qué cláusula limita el resultado a los primeros 10 registros?", code: "SELECT ___ 10 FirstName\nFROM Sales.Customer;", options: ["LIMIT", "FIRST", "TOP", "FETCH"], answer: 2, explanation: "En SQL Server, TOP limita el número o porcentaje de filas devueltas.", interview: "¿TOP 10 garantiza cuáles son los 10 registros? Solo si usas ORDER BY." },
  { prompt: "¿Cómo obtienes el 50% de las filas en SQL Server?", code: "SELECT ___ 50 PERCENT *\nFROM Sales.Customer;", options: ["TOP", "HALF", "LIMIT", "SAMPLE"], answer: 0, explanation: "TOP acepta un número o un porcentaje seguido de PERCENT.", interview: "¿Qué diferencia práctica hay entre TOP 10 y TOP 50 PERCENT?" },
  { prompt: "¿Qué palabra elimina ocupaciones repetidas del resultado?", code: "SELECT ___ Occupation\nFROM Sales.Customer;", options: ["UNIQUE", "DISTINCT", "ONLY", "DEDUP"], answer: 1, explanation: "DISTINCT devuelve una sola vez cada combinación distinta de valores seleccionados.", interview: "¿En qué puede influir DISTINCT en el rendimiento?" },
  { prompt: "Sin ORDER BY, ¿qué puedes afirmar sobre el orden de las filas?", code: "SELECT TOP 10 *\nFROM Sales.Customer;", options: ["Siempre será por CustomerID", "Siempre será alfabético", "No hay un orden garantizado", "Será por fecha de creación"], answer: 2, explanation: "Una tabla representa un conjunto; SQL Server puede devolver sus filas en cualquier orden sin ORDER BY.", interview: "¿Cómo harías que una consulta sea determinista?" },
  { prompt: "¿Qué práctica mejora la legibilidad al pedir solo los datos necesarios?", code: "SELECT ___, ___, ___\nFROM Sales.Customer;", options: ["Usar columnas explícitas", "Usar siempre *", "Quitar FROM", "Duplicar las columnas"], answer: 0, explanation: "Enumerar las columnas documenta la intención y evita transferir datos innecesarios.", interview: "¿Qué beneficios tiene proyectar solo las columnas requeridas?" },
];

export function SqlQuestionBank() {
  const [mode, setMode] = useState<"practice" | "interview">("practice");
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [answered, setAnswered] = useState(false);
  const question = selectQuestions[index];
  const next = () => { setIndex((value) => (value + 1) % selectQuestions.length); setSelected(null); setAnswered(false); };
  return <section className="sql-question-bank"><div className="sql-bank-heading"><div><p className="eyebrow">PRÁCTICA POR TEMA · SELECT</p><h3>10 preguntas para dominar SELECT</h3><p>Basadas en el demo de seleccionar datos de AdventureWorks.</p></div><span className="sql-bank-count">{index + 1} / 10</span></div><div className="sql-mode-toggle"><button type="button" className={mode === "practice" ? "active" : ""} onClick={() => { setMode("practice"); setSelected(null); setAnswered(false); }}>Práctica guiada</button><button type="button" className={mode === "interview" ? "active" : ""} onClick={() => { setMode("interview"); setSelected(null); setAnswered(false); }}>Modo entrevista</button></div>{mode === "interview" && <div className="sql-interview-prompt"><b>Pregunta de entrevista</b><span>{question.interview}</span></div>}<div className="sql-bank-card"><p className="sql-bank-question">{question.prompt}</p><pre className="sql-code-block"><code>{question.code}</code></pre><div className="sql-quiz-options">{question.options.map((option, optionIndex) => <button type="button" key={option} className={`${selected === optionIndex ? "selected" : ""} ${answered && optionIndex === question.answer ? "correct" : ""} ${answered && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} onClick={() => !answered && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{answered && <p className={`sql-quiz-feedback ${selected === question.answer ? "ok" : "retry"}`}>{selected === question.answer ? `¡Correcto! ${question.explanation}` : `Repasemos: ${question.explanation}`}</p>}<div className="sql-bank-actions">{!answered ? <button type="button" className="primary-cta" disabled={selected === null} onClick={() => setAnswered(true)}>Comprobar respuesta <span>→</span></button> : <button type="button" className="primary-cta" onClick={next}>{index === selectQuestions.length - 1 ? "Reiniciar tema" : "Siguiente pregunta"} <span>→</span></button>}</div></div></section>;
}
