"use client";

import { useEffect, useState } from "react";

type SqlQuestion = { prompt: string; code: string; options: string[]; answer: number; explanation: string; interview: string };
const selectQuestions: SqlQuestion[] = [
  { prompt: "¿Qué consulta devuelve el nombre de cada cliente?", code: "___ FirstName\nFROM Sales.Customer;", options: ["SELECT", "GET", "READ", "SHOW"], answer: 0, explanation: "SELECT indica las columnas que quieres devolver.", interview: "Explica la estructura mínima de una consulta SELECT." },
  { prompt: "¿Qué cláusula indica de qué tabla vienen los datos?", code: "SELECT FirstName\n___ Sales.Customer;", options: ["IN", "FROM", "TABLE", "SOURCE"], answer: 1, explanation: "FROM especifica la tabla de origen.", interview: "¿Qué diferencia hay entre SELECT y FROM?" },
  { prompt: "¿Cómo seleccionarías todas las columnas de Customer?", code: "SELECT ___\nFROM Sales.Customer;", options: ["ALL", "COLUMNS", "*", "EVERY"], answer: 2, explanation: "El asterisco representa todas las columnas.", interview: "¿Por qué puede ser mala idea usar SELECT * en producción?" },
  { prompt: "¿Cómo cambiarías el nombre de una columna en el resultado?", code: "SELECT FirstName ___ Nombre\nFROM Sales.Customer;", options: ["RENAME", "AS", "TO", "ALIAS"], answer: 1, explanation: "AS crea un alias para el resultado.", interview: "¿Un alias cambia la columna original?" },
  { prompt: "¿Qué expresión crea FullName uniendo nombre y apellido?", code: "SELECT FirstName + ' ' + ___ AS FullName\nFROM Sales.Customer;", options: ["Name", "Surname", "LastName", "CustomerName"], answer: 2, explanation: "El operador + concatena texto fila por fila.", interview: "¿Qué ocurre si uno de los valores contiene NULL?" },
  { prompt: "¿Qué cláusula limita el resultado a 10 registros?", code: "SELECT ___ 10 FirstName\nFROM Sales.Customer;", options: ["LIMIT", "FIRST", "TOP", "FETCH"], answer: 2, explanation: "En SQL Server, TOP limita las filas.", interview: "¿TOP 10 garantiza cuáles son los 10 registros?" },
  { prompt: "¿Cómo obtienes el 50% de las filas en SQL Server?", code: "SELECT ___ 50 PERCENT *\nFROM Sales.Customer;", options: ["TOP", "HALF", "LIMIT", "SAMPLE"], answer: 0, explanation: "TOP acepta un número o porcentaje.", interview: "¿Qué diferencia hay entre TOP 10 y TOP 50 PERCENT?" },
  { prompt: "¿Qué palabra elimina ocupaciones repetidas?", code: "SELECT ___ Occupation\nFROM Sales.Customer;", options: ["UNIQUE", "DISTINCT", "ONLY", "DEDUP"], answer: 1, explanation: "DISTINCT devuelve valores únicos.", interview: "¿En qué puede influir DISTINCT en el rendimiento?" },
  { prompt: "Sin ORDER BY, ¿qué puedes afirmar sobre el orden?", code: "SELECT TOP 10 *\nFROM Sales.Customer;", options: ["Siempre será por ID", "Siempre será alfabético", "No hay un orden garantizado", "Será por fecha"], answer: 2, explanation: "Sin ORDER BY SQL Server puede devolver filas en cualquier orden.", interview: "¿Cómo harías que la consulta fuera determinista?" },
  { prompt: "¿Qué práctica mejora la legibilidad al pedir datos?", code: "SELECT ___, ___, ___\nFROM Sales.Customer;", options: ["Usar columnas explícitas", "Usar siempre *", "Quitar FROM", "Duplicar columnas"], answer: 0, explanation: "Enumerar columnas documenta la intención y evita datos innecesarios.", interview: "¿Qué beneficios tiene proyectar solo las columnas requeridas?" },
];
const filterQuestions: SqlQuestion[] = [
  { prompt: "¿Qué cláusula filtra las filas?", code: "SELECT * FROM Customer\n___ FirstName <> 'Sam';", options: ["WHERE", "FILTER", "HAVING", "WHEN"], answer: 0, explanation: "WHERE conserva las filas cuya condición es verdadera.", interview: "¿Cuál es la diferencia entre WHERE y HAVING?" },
  { prompt: "¿Qué operador significa no es igual?", code: "WHERE FirstName ___ 'Sam';", options: ["!=", "<>", "Ambos A y B", "NOT ="], answer: 2, explanation: "SQL Server acepta <> y !=.", interview: "¿Qué operador de desigualdad prefieres?" },
  { prompt: "¿Qué patrón encuentra nombres que empiezan con Sam?", code: "WHERE FirstName LIKE ___;", options: ["'Sam'", "'Sam%'", "'%Sam'", "'_Sam'"], answer: 1, explanation: "% representa cero o más caracteres.", interview: "Explica la diferencia entre % y _." },
  { prompt: "¿Qué operador exige ambas condiciones?", code: "WHERE FirstName LIKE 'Sam%' ___ Income >= 50000;", options: ["OR", "AND", "BOTH", "WITH"], answer: 1, explanation: "AND requiere que ambas expresiones sean verdaderas.", interview: "¿Cómo cambia el resultado al usar OR?" },
  { prompt: "¿Qué palabra expresa un rango inclusivo?", code: "WHERE Income ___ 50000 AND 100000;", options: ["RANGE", "BETWEEN", "IN", "FROM"], answer: 1, explanation: "BETWEEN incluye sus límites.", interview: "¿BETWEEN incluye los extremos?" },
  { prompt: "¿Qué operador comprueba una lista de valores?", code: "WHERE Income ___ (20000, 30000);", options: ["IN", "ANY", "LIST", "MATCH"], answer: 0, explanation: "IN comprueba coincidencias con una lista.", interview: "¿Cuándo usarías IN en lugar de OR?" },
  { prompt: "¿Qué operador devuelve filas si se cumple una condición?", code: "WHERE Income < 50000 ___ Income > 100000;", options: ["AND", "OR", "EITHER", "PLUS"], answer: 1, explanation: "OR es verdadero si al menos una expresión es verdadera.", interview: "¿Qué riesgo hay al mezclar AND y OR?" },
  { prompt: "¿Por qué usar paréntesis en condiciones complejas?", code: "WHERE Name LIKE 'Sam%'\nAND (Income < 50000 OR Income > 100000);", options: ["Controlan la precedencia lógica", "Ordenan filas", "Crean columnas", "No tienen efecto"], answer: 0, explanation: "Agrupan la lógica y hacen explícita la intención.", interview: "Explica la precedencia de AND frente a OR." },
  { prompt: "¿Qué encuentra LIKE '%son'?", code: "WHERE LastName LIKE '%son';", options: ["Termina en son", "Empieza por son", "Es exactamente son", "Tiene tres letras"], answer: 0, explanation: "% al inicio permite cualquier texto antes de son.", interview: "¿Cómo buscarías son en cualquier posición?" },
  { prompt: "¿Qué práctica evita resultados inesperados?", code: "WHERE Name LIKE 'Sam%'\nAND (Income BETWEEN 50000 AND 99999);", options: ["Usar paréntesis y condiciones claras", "Eliminar WHERE", "Usar siempre *", "Duplicar la tabla"], answer: 0, explanation: "Agrupar la lógica hace explícita la intención del filtro.", interview: "¿Cómo probarías una condición compleja?" },
];

function RoundSummary({ title, score, onRestart }: { title: string; score: number; onRestart: () => void }) {
  return <div className="sql-round-summary"><div className="sql-summary-medal">{score >= 8 ? "★" : "✓"}</div><p className="eyebrow">TEMA COMPLETADO</p><h3>{title}</h3><strong>{score} / 10 correctas</strong><p>{score === 10 ? "¡Dominaste este tema!" : score >= 7 ? "¡Muy bien! Repasa los errores para llegar al 10." : "Buen intento. Repite el tema y vuelve a intentarlo."}</p><button type="button" className="primary-cta" onClick={onRestart}>Repetir las 10 preguntas <span>↻</span></button></div>;
}

export function SqlQuestionBank({ progress, onProgress }: { progress: { selectIndex: number; selectAnswered: number; selectCorrect: number; selectCompleted: boolean; selectLastScore: number }; onProgress: (changes: Partial<typeof progress>) => void }) {
  const [mode, setMode] = useState<"practice" | "interview">("practice"); const [index, setIndex] = useState(progress.selectIndex); const [selected, setSelected] = useState<number | null>(null); const [answered, setAnswered] = useState(false); const [roundCorrect, setRoundCorrect] = useState(0); const [showSummary, setShowSummary] = useState(progress.selectCompleted); const question = selectQuestions[index];
  useEffect(() => { setIndex(progress.selectIndex); setShowSummary(progress.selectCompleted); }, [progress.selectIndex, progress.selectCompleted]);
  const submit = () => { if (selected === null || answered) return; const correct = selected === question.answer; const total = roundCorrect + (correct ? 1 : 0); setRoundCorrect(total); setAnswered(true); onProgress({ selectAnswered: progress.selectAnswered + 1, selectCorrect: progress.selectCorrect + (correct ? 1 : 0), ...(index === 9 ? { selectCompleted: true, selectLastScore: total } : {}) }); };
  const next = () => { if (index === 9) { setShowSummary(true); return; } const nextIndex = index + 1; setIndex(nextIndex); onProgress({ selectIndex: nextIndex }); setSelected(null); setAnswered(false); };
  const restart = () => { setIndex(0); setRoundCorrect(0); setSelected(null); setAnswered(false); setShowSummary(false); onProgress({ selectIndex: 0, selectCompleted: false, selectLastScore: 0 }); };
  return <section className="sql-question-bank">{showSummary ? <RoundSummary title="10 preguntas para dominar SELECT" score={progress.selectLastScore || roundCorrect} onRestart={restart} /> : <><div className="sql-bank-heading"><div><p className="eyebrow">PRÁCTICA POR TEMA · SELECT</p><h3>10 preguntas para dominar SELECT</h3><p>Basadas en el demo de seleccionar datos de AdventureWorks.</p></div><span className="sql-bank-count">{index + 1} / 10</span></div><div className="sql-mode-toggle"><button type="button" className={mode === "practice" ? "active" : ""} onClick={() => { setMode("practice"); setSelected(null); setAnswered(false); }}>Práctica guiada</button><button type="button" className={mode === "interview" ? "active" : ""} onClick={() => { setMode("interview"); setSelected(null); setAnswered(false); }}>Modo entrevista</button></div>{mode === "interview" && <div className="sql-interview-prompt"><b>Pregunta de entrevista</b><span>{question.interview}</span></div>}<div className="sql-bank-card"><p className="sql-bank-question">{question.prompt}</p><pre className="sql-code-block"><code>{question.code}</code></pre><div className="sql-quiz-options">{question.options.map((option, optionIndex) => <button type="button" key={option} className={`${selected === optionIndex ? "selected" : ""} ${answered && optionIndex === question.answer ? "correct" : ""} ${answered && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} onClick={() => !answered && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{answered && <p className={`sql-quiz-feedback ${selected === question.answer ? "ok" : "retry"}`}>{selected === question.answer ? `¡Correcto! ${question.explanation}` : `Repasemos: ${question.explanation}`}</p>}<div className="sql-bank-actions">{!answered ? <button type="button" className="primary-cta" disabled={selected === null} onClick={submit}>Comprobar respuesta <span>→</span></button> : <button type="button" className="primary-cta" onClick={next}>{index === 9 ? "Ver resumen" : "Siguiente pregunta"} <span>→</span></button>}</div></div></>}</section>;
}

export function SqlFilterQuestionBank({ progress, onProgress }: { progress: { filterIndex: number; filterAnswered: number; filterCorrect: number; filterCompleted: boolean; filterLastScore: number }; onProgress: (changes: Partial<typeof progress>) => void }) {
  const [index, setIndex] = useState(progress.filterIndex); const [selected, setSelected] = useState<number | null>(null); const [answered, setAnswered] = useState(false); const [roundCorrect, setRoundCorrect] = useState(0); const [showSummary, setShowSummary] = useState(progress.filterCompleted); const question = filterQuestions[index];
  useEffect(() => { setIndex(progress.filterIndex); setShowSummary(progress.filterCompleted); }, [progress.filterIndex, progress.filterCompleted]);
  const submit = () => { if (selected === null || answered) return; const correct = selected === question.answer; const total = roundCorrect + (correct ? 1 : 0); setRoundCorrect(total); setAnswered(true); onProgress({ filterAnswered: progress.filterAnswered + 1, filterCorrect: progress.filterCorrect + (correct ? 1 : 0), ...(index === 9 ? { filterCompleted: true, filterLastScore: total } : {}) }); };
  const next = () => { if (index === 9) { setShowSummary(true); return; } const nextIndex = index + 1; setIndex(nextIndex); onProgress({ filterIndex: nextIndex }); setSelected(null); setAnswered(false); };
  const restart = () => { setIndex(0); setRoundCorrect(0); setSelected(null); setAnswered(false); setShowSummary(false); onProgress({ filterIndex: 0, filterCompleted: false, filterLastScore: 0 }); };
  return <section className="sql-question-bank sql-filter-bank">{showSummary ? <RoundSummary title="10 preguntas para dominar WHERE" score={progress.filterLastScore || roundCorrect} onRestart={restart} /> : <><div className="sql-bank-heading"><div><p className="eyebrow">PRÁCTICA POR TEMA · WHERE</p><h3>10 preguntas para dominar el filtrado</h3><p>Basadas en el demo de Filtering Data con AdventureWorks.</p></div><span className="sql-bank-count">{index + 1} / 10</span></div><div className="sql-mode-toggle"><span className="sql-filter-label">Modo entrevista incluido en cada pregunta</span></div><div className="sql-bank-card"><p className="sql-bank-question">{question.prompt}</p><pre className="sql-code-block"><code>{question.code}</code></pre><div className="sql-quiz-options">{question.options.map((option, optionIndex) => <button type="button" key={option} className={`${selected === optionIndex ? "selected" : ""} ${answered && optionIndex === question.answer ? "correct" : ""} ${answered && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} onClick={() => !answered && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{answered && <div className="sql-interview-prompt"><b>Entrevista:</b><span>{question.interview}</span></div>}<div className="sql-bank-actions">{!answered ? <button type="button" className="primary-cta" disabled={selected === null} onClick={submit}>Comprobar respuesta <span>→</span></button> : <button type="button" className="primary-cta" onClick={next}>{index === 9 ? "Ver resumen" : "Siguiente pregunta"} <span>→</span></button>}</div></div></>}</section>;
}
