"use client";

import { useEffect, useState } from "react";

type SqlQuestion = { prompt: string; code: string; options: string[]; answer: number; explanation: string; interview: string };

const selectQuestions: SqlQuestion[] = [
  { prompt: "¿Qué consulta devuelve el nombre de cada cliente?", code: "___ FirstName\nFROM Sales.Customer;", options: ["SELECT", "GET", "READ", "SHOW"], answer: 0, explanation: "SELECT indica las columnas que quieres devolver.", interview: "Explica la estructura mínima de una consulta SELECT." },
  { prompt: "¿Qué cláusula indica de qué tabla vienen los datos?", code: "SELECT FirstName\n___ Sales.Customer;", options: ["IN", "FROM", "TABLE", "SOURCE"], answer: 1, explanation: "FROM especifica la tabla o conjunto de tablas de origen.", interview: "¿Qué diferencia hay entre SELECT y FROM?" },
  { prompt: "¿Cómo seleccionarías todas las columnas de Customer?", code: "SELECT ___\nFROM Sales.Customer;", options: ["ALL", "COLUMNS", "*", "EVERY"], answer: 2, explanation: "El asterisco representa todas las columnas, aunque conviene evitarlo cuando no necesitas todas.", interview: "¿Por qué puede ser mala idea usar SELECT * en producción?" },
  { prompt: "¿Cómo cambiarías el nombre de una columna en el resultado?", code: "SELECT FirstName ___ Nombre\nFROM Sales.Customer;", options: ["RENAME", "AS", "TO", "ALIAS"], answer: 1, explanation: "AS crea un alias para mostrar un nombre más claro en el resultado.", interview: "¿Un alias cambia la columna en la tabla? No, solo el nombre del resultado." },
  { prompt: "¿Qué expresión crea FullName uniendo nombre y apellido?", code: "SELECT FirstName + ' ' + ___ AS FullName\nFROM Sales.Customer;", options: ["Name", "Surname", "LastName", "CustomerName"], answer: 2, explanation: "El operador + concatena valores de texto fila por fila.", interview: "¿Qué debes considerar si FirstName o LastName contiene NULL?" },
  { prompt: "¿Qué cláusula limita el resultado a los primeros 10 registros?", code: "SELECT ___ 10 FirstName\nFROM Sales.Customer;", options: ["LIMIT", "FIRST", "TOP", "FETCH"], answer: 2, explanation: "En SQL Server, TOP limita el número o porcentaje de filas devueltas.", interview: "¿TOP 10 garantiza cuáles son los 10 registros? Solo si usas ORDER BY." },
  { prompt: "¿Cómo obtienes el 50% de las filas en SQL Server?", code: "SELECT ___ 50 PERCENT *\nFROM Sales.Customer;", options: ["TOP", "HALF", "LIMIT", "SAMPLE"], answer: 0, explanation: "TOP acepta un número o un porcentaje seguido de PERCENT.", interview: "¿Qué diferencia práctica hay entre TOP 10 y TOP 50 PERCENT?" },
  { prompt: "¿Qué palabra elimina ocupaciones repetidas del resultado?", code: "SELECT ___ Occupation\nFROM Sales.Customer;", options: ["UNIQUE", "DISTINCT", "ONLY", "DEDUP"], answer: 1, explanation: "DISTINCT devuelve una sola vez cada combinación distinta de valores seleccionados.", interview: "¿En qué puede influir DISTINCT en el rendimiento?" },
  { prompt: "Sin ORDER BY, ¿qué puedes afirmar sobre el orden de las filas?", code: "SELECT TOP 10 *\nFROM Sales.Customer;", options: ["Siempre será por CustomerID", "Siempre será alfabético", "No hay un orden garantizado", "Será por fecha de creación"], answer: 2, explanation: "Una tabla representa un conjunto; SQL Server puede devolver sus filas en cualquier orden sin ORDER BY.", interview: "¿Cómo harías que una consulta sea determinista?" },
  { prompt: "¿Qué práctica mejora la legibilidad al pedir solo los datos necesarios?", code: "SELECT ___, ___, ___\nFROM Sales.Customer;", options: ["Usar columnas explícitas", "Usar siempre *", "Quitar FROM", "Duplicar las columnas"], answer: 0, explanation: "Enumerar las columnas documenta la intención y evita transferir datos innecesarios.", interview: "¿Qué beneficios tiene proyectar solo las columnas requeridas?" },
];

const filterQuestions: SqlQuestion[] = [
  { prompt: "¿Qué cláusula filtra las filas?", code: "SELECT * FROM Customer\n___ FirstName <> 'Sam';", options: ["WHERE", "FILTER", "HAVING", "WHEN"], answer: 0, explanation: "WHERE conserva las filas cuya condición es verdadera.", interview: "¿Cuál es la diferencia entre WHERE y HAVING?" },
  { prompt: "¿Qué operador significa no es igual?", code: "WHERE FirstName ___ 'Sam';", options: ["!=", "<>", "Ambos A y B", "NOT ="], answer: 2, explanation: "SQL Server acepta <> y != para expresar desigualdad.", interview: "¿Qué operador de desigualdad prefieres?" },
  { prompt: "¿Qué patrón encuentra nombres que empiezan con Sam?", code: "WHERE FirstName LIKE ___;", options: ["'Sam'", "'Sam%'", "'%Sam'", "'_Sam'"], answer: 1, explanation: "% representa cero o más caracteres.", interview: "Explica la diferencia entre % y _." },
  { prompt: "¿Qué operador exige ambas condiciones?", code: "WHERE FirstName LIKE 'Sam%' ___ Income >= 50000;", options: ["OR", "AND", "BOTH", "WITH"], answer: 1, explanation: "AND requiere que ambas expresiones sean verdaderas.", interview: "¿Cómo cambia el resultado al usar OR?" },
  { prompt: "¿Qué palabra expresa un rango inclusivo?", code: "WHERE Income ___ 50000 AND 100000;", options: ["RANGE", "BETWEEN", "IN", "FROM"], answer: 1, explanation: "BETWEEN incluye sus límites inferior y superior.", interview: "¿BETWEEN incluye los extremos?" },
  { prompt: "¿Qué operador comprueba una lista de valores?", code: "WHERE Income ___ (20000, 30000);", options: ["IN", "ANY", "LIST", "MATCH"], answer: 0, explanation: "IN verifica si el valor coincide con un elemento de la lista.", interview: "¿Cuándo usarías IN en lugar de OR?" },
  { prompt: "¿Qué operador devuelve filas si se cumple al menos una condición?", code: "WHERE Income < 50000 ___ Income > 100000;", options: ["AND", "OR", "EITHER", "PLUS"], answer: 1, explanation: "OR es verdadero cuando al menos una expresión es verdadera.", interview: "¿Qué riesgo hay al mezclar AND y OR?" },
  { prompt: "¿Por qué usar paréntesis en condiciones complejas?", code: "WHERE Name LIKE 'Sam%'\nAND (Income < 50000 OR Income > 100000);", options: ["Controlan la precedencia lógica", "Ordenan filas", "Crean columnas", "No tienen efecto"], answer: 0, explanation: "Agrupan OR para que se evalúe junto antes de combinarlo con AND.", interview: "Explica la precedencia de AND frente a OR." },
  { prompt: "¿Qué encuentra LIKE '%son'?", code: "WHERE LastName LIKE '%son';", options: ["Termina en son", "Empieza por son", "Es exactamente son", "Tiene tres letras"], answer: 0, explanation: "% al inicio permite cualquier texto antes de son.", interview: "¿Cómo buscarías son en cualquier posición?" },
  { prompt: "¿Qué práctica evita resultados inesperados?", code: "WHERE Name LIKE 'Sam%'\nAND (Income BETWEEN 50000 AND 99999);", options: ["Usar paréntesis y condiciones claras", "Eliminar WHERE", "Usar siempre *", "Duplicar la tabla"], answer: 0, explanation: "Agrupar la lógica hace explícita la intención del filtro.", interview: "¿Cómo probarías una condición compleja?" },
];

export function SqlQuestionBank({ progress, onProgress }: { progress: { selectIndex: number; selectAnswered: number; selectCorrect: number }; onProgress: (changes: { selectIndex?: number; selectAnswered?: number; selectCorrect?: number }) => void }) {
  const [mode, setMode] = useState<"practice" | "interview">("practice");
  const [index, setIndex] = useState(progress.selectIndex);
  const [selected, setSelected] = useState<number | null>(null);
  const [answered, setAnswered] = useState(false);
  const questions = selectQuestions;
  const question = questions[index];
  useEffect(() => { setIndex(progress.selectIndex); }, [progress.selectIndex]);
  useEffect(() => { if (answered) onProgress({ selectAnswered: progress.selectAnswered + 1, selectCorrect: progress.selectCorrect + (selected === question.answer ? 1 : 0) }); }, [answered]);
  const next = () => { const nextIndex = (index + 1) % questions.length; setIndex(nextIndex); onProgress({ selectIndex: nextIndex }); setSelected(null); setAnswered(false); };
  const checkAnswer = () => { setAnswered(true); onProgress({ selectAnswered: progress.selectAnswered + 1, selectCorrect: progress.selectCorrect + (selected === question.answer ? 1 : 0) }); };
  return <section className="sql-question-bank"><div className="sql-bank-heading"><div><p className="eyebrow">PRÁCTICA POR TEMA · SELECT</p><h3>10 preguntas para dominar SELECT</h3><p>Basadas en el demo de seleccionar datos de AdventureWorks.</p></div><span className="sql-bank-count">{index + 1} / 10</span></div><div className="sql-mode-toggle"><button type="button" className={mode === "practice" ? "active" : ""} onClick={() => { setMode("practice"); setSelected(null); setAnswered(false); }}>Práctica guiada</button><button type="button" className={mode === "interview" ? "active" : ""} onClick={() => { setMode("interview"); setSelected(null); setAnswered(false); }}>Modo entrevista</button></div>{mode === "interview" && <div className="sql-interview-prompt"><b>Pregunta de entrevista</b><span>{question.interview}</span></div>}<div className="sql-bank-card"><p className="sql-bank-question">{question.prompt}</p><pre className="sql-code-block"><code>{question.code}</code></pre><div className="sql-quiz-options">{question.options.map((option, optionIndex) => <button type="button" key={option} className={`${selected === optionIndex ? "selected" : ""} ${answered && optionIndex === question.answer ? "correct" : ""} ${answered && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} onClick={() => !answered && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{answered && <p className={`sql-quiz-feedback ${selected === question.answer ? "ok" : "retry"}`}>{selected === question.answer ? `¡Correcto! ${question.explanation}` : `Repasemos: ${question.explanation}`}</p>}<div className="sql-bank-actions">{!answered ? <button type="button" className="primary-cta" disabled={selected === null} onClick={() => setAnswered(true)}>Comprobar respuesta <span>→</span></button> : <button type="button" className="primary-cta" onClick={next}>{index === selectQuestions.length - 1 ? "Reiniciar tema" : "Siguiente pregunta"} <span>→</span></button>}</div></div></section>;
}

export function SqlFilterQuestionBank({ progress, onProgress }: { progress: { filterIndex: number; filterAnswered: number; filterCorrect: number }; onProgress: (changes: { filterIndex?: number; filterAnswered?: number; filterCorrect?: number }) => void }) {
  const [index, setIndex] = useState(progress.filterIndex);
  const [selected, setSelected] = useState<number | null>(null);
  const [answered, setAnswered] = useState(false);
  const question = filterQuestions[index];
  useEffect(() => { setIndex(progress.filterIndex); }, [progress.filterIndex]);
  useEffect(() => { if (answered) onProgress({ filterAnswered: progress.filterAnswered + 1, filterCorrect: progress.filterCorrect + (selected === question.answer ? 1 : 0) }); }, [answered]);
  const next = () => { const nextIndex = (index + 1) % filterQuestions.length; setIndex(nextIndex); onProgress({ filterIndex: nextIndex }); setSelected(null); setAnswered(false); };
  const checkAnswer = () => { setAnswered(true); onProgress({ filterAnswered: progress.filterAnswered + 1, filterCorrect: progress.filterCorrect + (selected === question.answer ? 1 : 0) }); };
  return <section className="sql-question-bank sql-filter-bank"><div className="sql-bank-heading"><div><p className="eyebrow">PRÁCTICA POR TEMA · WHERE</p><h3>10 preguntas para dominar el filtrado</h3><p>Basadas en el demo de Filtering Data con AdventureWorks.</p></div><span className="sql-bank-count">{index + 1} / 10</span></div><div className="sql-mode-toggle"><span className="sql-filter-label">Modo entrevista incluido en cada pregunta</span></div><div className="sql-bank-card"><p className="sql-bank-question">{question.prompt}</p><pre className="sql-code-block"><code>{question.code}</code></pre><div className="sql-quiz-options">{question.options.map((option, optionIndex) => <button type="button" key={option} className={`${selected === optionIndex ? "selected" : ""} ${answered && optionIndex === question.answer ? "correct" : ""} ${answered && selected === optionIndex && optionIndex !== question.answer ? "wrong" : ""}`} onClick={() => !answered && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{answered && <div className="sql-interview-prompt"><b>Entrevista:</b><span>{question.interview}</span></div>}<div className="sql-bank-actions">{!answered ? <button type="button" className="primary-cta" disabled={selected === null} onClick={() => setAnswered(true)}>Comprobar respuesta <span>→</span></button> : <button type="button" className="primary-cta" onClick={next}>{index === filterQuestions.length - 1 ? "Reiniciar tema" : "Siguiente pregunta"} <span>→</span></button>}</div></div></section>;
}
