"use client";
import { useMemo, useState } from "react";

type StudyQuestion={prompt:string;options:string[];answer:number;why:string;code?:string};
type PatternExample={name:string;explanation:string;kid:string;code:string};
type PatternFamily={name:string;question:string;meaning:string;kid:string;patterns:string;example:string};
type StudyTopic={id:string;title:string;tags:string[];summary:string;code:string;points:string[];trap:string;kid?:string;exercises?:string[];examples?:PatternExample[];families?:PatternFamily[];questions?:StudyQuestion[]};

const encapsulationQuestions:StudyQuestion[]=[
 {prompt:"¿Qué acceso permite usar un miembro desde cualquier código que pueda ver el tipo?",options:["public","private","protected","internal"],answer:0,why:"public expone el miembro fuera del tipo. Debe usarse solo cuando forma parte del contrato público."},
 {prompt:"¿Qué acceso limita un miembro para que solo lo use el tipo que lo declara?",options:["protected","private","public","static"],answer:1,why:"private es el nivel más restrictivo: el miembro solo es accesible dentro del tipo que lo declara."},
 {prompt:"¿Qué acceso permite usar un miembro desde la clase y sus clases derivadas?",options:["internal","protected","private","public"],answer:1,why:"protected permite acceso dentro del tipo y desde tipos derivados, pero no desde cualquier clase externa."},
 {prompt:"¿Qué significa internal en un ensamblado de C#?",options:["Visible dentro del mismo assembly, salvo configuraciones especiales","Visible solo dentro de la clase","Visible solo en clases derivadas","Obliga a que el miembro sea static"],answer:0,why:"internal limita el acceso al mismo ensamblado. Es útil para código compartido dentro del proyecto sin convertirlo en API pública."},
 {prompt:"En este código, ¿qué línea compila desde otra clase del mismo proyecto?",options:["user.PublicName","user.secret","user.ProtectedName","User.staticCounter si es private"],answer:0,why:"Solo el miembro public es accesible desde una clase externa; private y protected tienen restricciones adicionales.",code:"class User\n{\n    public string PublicName;\n    private string secret;\n    protected string ProtectedName;\n}"},
 {prompt:"¿Qué expresa static en un miembro?",options:["Pertenece al tipo y no a una instancia concreta","Lo hace siempre private","Solo pueden usarlo las clases derivadas","Lo convierte en una constante"],answer:0,why:"static indica que el miembro se accede mediante el tipo y se comparte a nivel de tipo; no define por sí solo public o private."},
 {prompt:"¿Cuál acceso protege mejor un campo interno que solo debe cambiarse mediante métodos?",options:["private","public","internal","protected"],answer:0,why:"private oculta el campo y permite controlar los cambios mediante métodos o propiedades públicas cuidadosamente diseñadas."},
 {prompt:"¿Qué combinación es válida para un contador compartido por todas las instancias, pero oculto desde fuera?",options:["private static int count;","public instance int count;","protected readonly static public count;","internal private count;"],answer:0,why:"private limita el acceso externo y static hace que exista un único miembro asociado al tipo, no uno por instancia."},
 {prompt:"¿Qué diferencia hay entre protected e internal?",options:["protected depende de la herencia; internal depende del ensamblado","protected siempre es público; internal siempre es privado","Ambos significan exactamente lo mismo","internal solo funciona con static"],answer:0,why:"protected autoriza al tipo y a sus derivados; internal autoriza al código del mismo ensamblado, aunque no exista herencia."},
 {prompt:"¿Cuál diseño aplica mejor encapsulamiento?",options:["Campo private y una propiedad o método público que valide los cambios","Todos los campos public para evitar métodos","Todos los miembros static","Usar protected para cualquier dato"],answer:0,why:"Encapsular es proteger el estado interno y exponer operaciones válidas, no simplemente hacer todo accesible."},
];

const studyTopics:StudyTopic[]=[
 {id:"class-struct-record",title:"class vs struct vs record",tags:["Tipos","POO","Entrevista"],summary:"Los tres pueden definir tipos, pero expresan semánticas diferentes: identidad y referencia, valor pequeño, o datos con igualdad por valor.",code:"class User { public int Id; }\nstruct Point { public int X, Y; }\nrecord UserDto(int Id);",points:["class es reference type y normalmente representa identidad de objeto.","struct es value type: se copia por valor y suele ser adecuado para valores pequeños.","record puede ser record class o record struct y ofrece igualdad basada en valores.","Una clase admite herencia de otra clase; un struct no hereda de clases, aunque puede implementar interfaces."],trap:"Un record no significa automáticamente que todo sea profundamente inmutable: sus propiedades y objetos internos requieren analizarse."},
 {id:"reference-value",title:"reference type vs value type",tags:["Tipos","Memoria"],summary:"La diferencia principal está en la semántica de copia. Un value type copia el valor; un reference type copia la referencia al objeto.",code:"int a = 1;\nint b = a;\nb++; // a sigue siendo 1\n\nvar x = new List<int>();\nvar y = x;\ny.Add(1); // x también ve el elemento",points:["int, bool, enum y struct son ejemplos de value types.","class, array, delegate y string son reference types.","Pasar una referencia por valor no clona automáticamente el objeto.","string es reference type, pero es inmutable; sus operaciones crean nuevas cadenas."],trap:"Reference type no significa que la variable contenga directamente el objeto; contiene una referencia al objeto."},
 {id:"pass-by-value",title:"pasar parámetros by value",tags:["Métodos","Memoria"],summary:"Por defecto, C# pasa los parámetros por valor. En un reference type se copia la referencia, por eso el método puede mutar el objeto apuntado, pero no reasignar la variable original.",code:"void Add(List<int> values)\n{\n    values.Add(10); // muta el objeto\n    values = new();  // no cambia la variable del llamador\n}",points:["Un parámetro value type por valor recibe una copia del valor.","Un parámetro reference type por valor recibe una copia de la referencia.","Mutar el objeto puede observarse fuera del método.","Reasignar el parámetro solo cambia la copia local de la referencia."],trap:"Decir simplemente que una clase siempre se pasa por referencia es impreciso; por defecto se pasa la referencia por valor."},
 {id:"ref-out",title:"ref y out",tags:["Métodos","Entrevista"],summary:"ref permite leer y modificar la variable del llamador; out permite producir un valor adicional y debe asignarse dentro del método.",code:"static void Increment(ref int value) => value++;\nstatic bool TryGet(out int value)\n{ value = 42; return true; }",points:["ref exige que la variable esté inicializada antes de la llamada.","out no exige inicialización previa, pero el método debe asignarlo antes de terminar.","TryParse usa out para devolver el resultado y bool para indicar éxito.","ref y out deben aparecer tanto en la declaración como en la llamada."],trap:"ref no es una forma de pasar cualquier objeto mágicamente: cambia el contrato para permitir reasignar la variable del llamador."},
 {id:"in-parameter",title:"parámetro in",tags:["Métodos","Value types"],summary:"in pasa un argumento por referencia de solo lectura. Puede evitar copias de structs grandes, pero el método no puede reasignar ni modificar el argumento a través de ese parámetro.",code:"static int Read(in Point point)\n    => point.X + point.Y;",points:["in comunica que el método no debe modificar el argumento.","El llamador entrega una variable compatible y el método recibe una referencia readonly.","No es lo mismo que ref: ref permite escritura.","Para tipos pequeños, la claridad suele importar más que una microoptimización."],trap:"in no convierte un reference type en inmutable; solo limita el parámetro y su asignación desde ese método."},
 {id:"boxing",title:"boxing y unboxing",tags:["Tipos","Memoria","Entrevista"],summary:"Boxing envuelve un value type dentro de un object o interfaz. Unboxing extrae el tipo compatible y puede fallar si el tipo no coincide.",code:"int number = 42;\nobject boxed = number;\nint copy = (int)boxed;",points:["Boxing crea un objeto que contiene una copia del value type.","Unboxing requiere el tipo correcto y una conversión explícita.","Las colecciones genéricas suelen evitar boxing innecesario.","El cast a un tipo incompatible produce una excepción."],trap:"Asignar un int a object no mantiene una referencia al int original; se crea una caja con una copia."},
];

studyTopics.push({
 id:"encapsulation",title:"Encapsulamiento y modificadores",tags:["POO","Acceso","Entrevista"],summary:"Encapsular es proteger el estado interno y exponer solo las operaciones válidas. public, private, protected e internal controlan quién puede acceder; static indica pertenencia al tipo, no un nivel de acceso.",code:"class Account\n{\n    private decimal balance;\n    public decimal Balance => balance;\n    protected void SetBalance(decimal value) => balance = value;\n    internal static string Area => \"billing\";\n}",points:["public: accesible desde código externo que pueda ver el tipo.","private: accesible solo dentro del tipo que lo declara.","protected: accesible dentro del tipo y desde clases derivadas.","internal: accesible dentro del mismo ensamblado.","static: pertenece al tipo y se comparte a nivel de tipo; no es public ni private por sí mismo."],trap:"static no es un modificador de acceso. Puede combinarse, por ejemplo, con private: private static int count;",questions:encapsulationQuestions
});

const designPatternQuestions:StudyQuestion[]=[
 {prompt:"¿Qué problema resuelve Factory Method?",options:["Centralizar la creación y elegir una implementación sin acoplar el consumidor a new concreto","Compartir una única instancia global","Agregar responsabilidades envolviendo objetos","Notificar automáticamente a suscriptores"],answer:0,why:"Factory encapsula la decisión de qué objeto concreto crear; el consumidor depende del contrato.",code:"INotifier notifier = NotifierFactory.Create(channel);"},
 {prompt:"¿Cuándo aporta valor Builder?",options:["Cuando un objeto complejo se construye paso a paso con opciones claras","Cuando solo existe una instancia global","Cuando necesitas convertir una interfaz en otra","Cuando quieres observar cambios"],answer:0,why:"Builder evita constructores enormes y separa la construcción de la representación final.",code:"var report = new ReportBuilder().WithTitle(title).AddSection(body).Build();"},
 {prompt:"¿Cuál es la alerta principal de Singleton?",options:["Introduce estado global y acoplamiento; debe justificarse","Nunca puede tener métodos","Solo funciona en structs","Obliga a usar herencia múltiple"],answer:0,why:"Singleton puede dificultar pruebas y ocultar dependencias. En .NET, DI suele ser una alternativa más explícita.",code:"services.AddSingleton<ICache, MemoryCache>();"},
 {prompt:"¿Qué hace Adapter?",options:["Convierte una interfaz existente en la interfaz que el consumidor espera","Crea una familia de objetos relacionados","Añade comportamiento por herencia profunda","Guarda cambios en una base"],answer:0,why:"Adapter integra una clase existente sin modificarla cuando su contrato no coincide con el esperado.",code:"IPayment payment = new LegacyPaymentAdapter(legacyClient);"},
 {prompt:"¿Qué describe mejor Decorator?",options:["Envuelve un objeto con el mismo contrato para agregar responsabilidades combinables","Selecciona un algoritmo mediante if","Crea objetos con constructor privado","Recorre un árbol"],answer:0,why:"Decorator conserva el contrato y añade comportamiento antes o después del objeto envuelto.",code:"IStream stream = new CompressionStream(new FileStream());"},
 {prompt:"¿Qué ventaja ofrece Strategy?",options:["Permite intercambiar algoritmos detrás de un contrato sin modificar el consumidor","Garantiza una instancia global","Convierte DTOs en entidades","Obliga a heredar de una base"],answer:0,why:"Strategy encapsula algoritmos intercambiables y reduce condicionales.",code:"calculator.Calculate(order, new TaxByCountryStrategy());"},
 {prompt:"¿Qué relación representa Observer?",options:["Un sujeto publica cambios y varios observadores reaccionan","Un objeto crea otro paso a paso","Una clase traduce interfaces","Un servicio guarda entidades"],answer:0,why:"Observer modela una relación uno-a-muchos de notificaciones. En .NET puede aparecer con eventos.",code:"order.StatusChanged += SendNotification;"},
 {prompt:"¿Qué encapsula Command?",options:["Una solicitud como objeto, permitiendo cola, historial, logging o undo","Una consulta SQL materializada","Una configuración global","Una relación de herencia"],answer:0,why:"Command separa quien solicita una acción de quien la ejecuta y trata la acción como dato.",code:"ICommand command = new ApproveInvoiceCommand(invoice);"},
 {prompt:"¿Qué idea expresa Repository?",options:["Abstraer el acceso a datos detrás de una interfaz","Crear siempre una tabla por clase","Reemplazar transacciones","Hacer entidades singleton"],answer:0,why:"Repository puede aislar persistencia cuando aporta valor; en EF Core una capa genérica no debe crearse por reflejo.",code:"IOrderRepository orders;"},
 {prompt:"¿Qué permite Dependency Injection?",options:["Entregar dependencias desde fuera y facilitar reemplazos y pruebas","Hacer toda la lógica static","Evitar interfaces","Ocultar dependencias en un service locator"],answer:0,why:"DI hace explícitas las colaboraciones y facilita pruebas. No es lo mismo que esconder dependencias globales.",code:"public Checkout(IPayment payment) { _payment = payment; }"},
 {prompt:"¿Qué diferencia clave hay entre Strategy y State?",options:["Strategy intercambia algoritmos; State cambia conducta según el estado interno","Strategy crea objetos y State traduce interfaces","Son exactamente el mismo patrón","State solo sirve para bases de datos"],answer:0,why:"Se parecen, pero State representa transiciones y comportamiento condicionado por el estado del objeto.",code:"context.TransitionTo(new PaidState());"},
 {prompt:"¿Qué afirmación sobre patrones es correcta?",options:["Son soluciones con nombre: se aplican si resuelven un problema y tienen un trade-off aceptable","Hay que usar uno por clase","Un patrón reemplaza los requisitos","Todos mejoran el rendimiento"],answer:0,why:"Los patrones ayudan a comunicar decisiones, pero también agregan abstracción y mantenimiento.",code:"problema -> patrón -> trade-off -> alternativa"},
];

const designPatternFamilies:PatternFamily[]=[
 {name:"Creacionales",question:"¿El problema principal es CÓMO crear el objeto?",meaning:"Controlan o simplifican la creación de objetos para no llenar el código de new, constructores gigantes o decisiones repetidas.",kid:"Es elegir cómo fabricar un juguete: una máquina sabe qué pieza construir y cómo armarla.",patterns:"Factory Method · Builder · Singleton",example:"Factory: NotifierFactory.Create(\"email\") decide qué notificador crear. Builder arma un Report por pasos."},
 {name:"Estructurales",question:"¿El problema principal es CÓMO conectar o combinar objetos?",meaning:"Organizan clases y objetos para formar estructuras más útiles sin cambiar necesariamente el código original.",kid:"Es usar adaptadores, capas o cajas para que piezas diferentes encajen y trabajen juntas.",patterns:"Adapter · Decorator · Facade · Composite",example:"Adapter traduce LegacyPayment a IPayment. Decorator envuelve IPayment para agregar logging."},
 {name:"De comportamiento",question:"¿El problema principal es CÓMO colaboran o cambian su comportamiento?",meaning:"Definen cómo se reparten responsabilidades, cómo se comunican los objetos y cómo se pueden intercambiar algoritmos.",kid:"Es decidir quién avisa, quién ejecuta una orden y qué forma de resolver un problema usarás.",patterns:"Strategy · Observer · Command · State",example:"Strategy cambia el cálculo de descuento. Observer avisa a varios suscriptores cuando cambia una orden."},
];

studyTopics.push({id:"design-patterns",title:"Patrones de diseño en C#",tags:["Diseño","C#","Entrevista"],summary:"Soluciones con nombre para problemas recurrentes de creación, composición y comportamiento. Aprende a elegirlos por el problema, no por moda.",kid:"Imagina que construyes con piezas de LEGO: algunos patrones crean la pieza correcta, otros conectan piezas distintas y otros hacen que varias piezas colaboren sin quedar pegadas para siempre.",code:"public interface IDiscount { decimal Apply(Order order); }\npublic sealed class Checkout(IDiscount discount)\n{\n    public decimal Total(Order order) => discount.Apply(order);\n}",families:designPatternFamilies,points:["Primero pregunta: ¿estoy resolviendo creación, estructura o colaboración? Esa respuesta identifica la familia.","Creacionales responden cómo crear: Factory decide la clase concreta; Builder construye paso a paso; Singleton limita instancias, con el costo de estado global.","Estructurales responden cómo conectar: Adapter traduce contratos; Decorator agrega capas; Facade simplifica una entrada.","De comportamiento responden cómo colaborar o variar: Strategy cambia algoritmos; Observer notifica; Command representa acciones; State cambia según estado.","Repository y Dependency Injection son técnicas/patrones de arquitectura; no son automáticamente la solución correcta para todo proyecto.","Un patrón no se elige por el nombre: explica problema, solución, trade-off y alternativa."],trap:"La trampa más común es pensar que conocer el nombre equivale a saber diseñar. En entrevista explica qué problema resuelve, qué costo introduce y por qué no elegirías otra opción.",exercises:["Clasifica cada caso: crear una notificación, conectar una API vieja, cambiar descuentos y avisar cambios de una orden.","Factory: crea EmailNotifier o SmsNotifier detrás de INotifier.","Builder: construye un Report con opciones sin un constructor de diez parámetros.","Strategy: reemplaza un switch de descuentos por IPricingStrategy e inyéctalo en Checkout.","Decorator: agrega logging y retry a IPayment sin modificar la implementación real.","Observer: publica cambios de Order y conecta dos reacciones sin acoplar Order a EmailService.","Entrevista: para cada ejercicio explica cómo agregarías una implementación y cómo la probarías."],examples:[
 {name:"Factory Method",explanation:"Una fábrica decide qué notificador crear y devuelve el contrato INotifier.",kid:"Es como pedir una bebida en una máquina: eliges la opción, pero no sabes cómo se prepara por dentro.",code:"INotifier n = NotifierFactory.Create(\"email\");\nn.Send(message);"},
 {name:"Builder",explanation:"Construye un objeto complejo por pasos, haciendo visibles las opciones.",kid:"Es como armar una hamburguesa eligiendo pan, carne y extras en orden.",code:"var report = new ReportBuilder()\n    .WithTitle(\"Ventas\")\n    .AddSection(data)\n    .Build();"},
 {name:"Singleton",explanation:"Controla una única instancia compartida, aunque en .NET normalmente conviene expresarlo con DI.",kid:"Es como una sola caja fuerte compartida: todos llegan a la misma, por eso hay que protegerla.",code:"services.AddSingleton<ICache, MemoryCache>();"},
 {name:"Adapter",explanation:"Envuelve una clase antigua para que cumpla el contrato moderno que tu código espera.",kid:"Es un adaptador de enchufe: conecta dos formas distintas sin cambiar la pared ni el aparato.",code:"IPayment p = new LegacyPaymentAdapter(oldGateway);"},
 {name:"Decorator",explanation:"Envuelve el mismo contrato para sumar logging, retry o validación sin modificar el objeto original.",kid:"Es ponerle capas a un regalo: cada capa agrega algo y el regalo sigue siendo un regalo.",code:"IPayment p = new LoggingPayment(realPayment);"},
 {name:"Strategy",explanation:"Permite intercambiar algoritmos detrás de una interfaz.",kid:"Es elegir una ruta distinta para llegar al mismo destino: cada ruta tiene su propia estrategia.",code:"var price = checkout.Total(order, new BlackFridayDiscount());"},
 {name:"Observer",explanation:"Un objeto publica un cambio y varios suscriptores reaccionan.",kid:"Es como avisar por altavoz: varias personas escuchan y cada una hace su tarea.",code:"order.StatusChanged += NotifyCustomer;\norder.StatusChanged += Audit;"},
 {name:"Command",explanation:"Convierte una acción en un objeto que puede encolarse, registrarse o deshacerse.",kid:"Es escribir una orden en una tarjeta: puedes guardarla, ejecutarla después o tacharla.",code:"ICommand command = new ApproveInvoiceCommand(invoice);\nqueue.Enqueue(command);"},
 {name:"Repository",explanation:"Oculta consultas y persistencia detrás de una interfaz orientada al caso de uso.",kid:"Es pedir un libro al bibliotecario sin recorrer tú todos los estantes.",code:"var orders = await repository.GetPendingAsync();"},
 {name:"Dependency Injection",explanation:"Entrega las colaboraciones desde fuera para que la clase no las cree ni las esconda.",kid:"En vez de fabricar tu propia herramienta, alguien te la entrega lista para usar.",code:"public Checkout(IPayment payment)\n{ _payment = payment; }"}
],questions:designPatternQuestions});

function StudyQuiz({questions}:{questions:StudyQuestion[]}){
 const [index,setIndex]=useState(0);const [selected,setSelected]=useState<number|null>(null);const [submitted,setSubmitted]=useState(false);const question=questions[index];const correct=selected===question.answer;
 const next=()=>{setIndex(i=>(i+1)%questions.length);setSelected(null);setSubmitted(false)};
 return <section className="study-quiz"><p className="eyebrow">PREGUNTA {index+1} DE {questions.length}</p><h4>{question.prompt}</h4>{question.code&&<pre><code>{question.code}</code></pre>}<p className="quiz-selection-hint">Selecciona una respuesta y después pulsa <b>Calificar respuesta</b>.</p><div className="study-quiz-options">{question.options.map((option,i)=><button type="button" key={option} aria-pressed={selected===i} className={`${!submitted&&selected===i?"selected":""} ${submitted&&i===question.answer?"correct":""} ${submitted&&selected===i&&i!==question.answer?"wrong":""}`} onClick={()=>{if(!submitted)setSelected(i)}}><span>{String.fromCharCode(65+i)}</span>{option}{!submitted&&selected===i&&<b className="quiz-picked">Seleccionada</b>}</button>)}</div>{submitted&&<div className={`study-quiz-feedback ${correct?"good":"bad"}`}><b>{correct?"¡Correcto!":"Esta no era. Repasemos."}</b><p>{question.why}</p><small><strong>Aclaración/truco:</strong> Explica qué problema resuelve y qué trade-off introduce antes de memorizar el nombre.</small></div>}{!submitted?<button type="button" className="primary-cta" disabled={selected===null} onClick={()=>setSubmitted(true)}>Calificar respuesta</button>:<button type="button" className="primary-cta" onClick={next}>Siguiente pregunta</button>}</section>;
}

export function StudyTopics(){
 const [quizQuestions,setQuizQuestions]=useState(encapsulationQuestions);
 return <><StudyTopicsGlossary onTopicChange={topic=>setQuizQuestions(topic.questions||encapsulationQuestions)}/><PatternExamplesPanel/><StudyQuiz questions={quizQuestions}/></>;
}

function PatternExamplesPanel(){
 const examples=studyTopics.find(topic=>topic.id==="design-patterns")?.examples||[];
 const families=studyTopics.find(topic=>topic.id==="design-patterns")?.families||[];
 return <section className="pattern-examples standalone"><div className="pattern-decision"><h3>Cómo diferenciar los patrones</h3><p><b>1. ¿Qué se está complicando?</b> Crear objetos → creacional. Conectar objetos → estructural. Coordinar comportamientos → comportamiento.</p><p><b>2. ¿Qué palabra describe el problema?</b> “Construir” apunta a Factory/Builder; “encajar o envolver” a Adapter/Decorator; “intercambiar, avisar o ejecutar” a Strategy/Observer/Command.</p><p><b>3. ¿Qué beneficio espero?</b> Menos acoplamiento, cambios localizados y código más fácil de probar. Si solo agrega clases sin resolver un problema, no es una buena aplicación del patrón.</p></div><h3>Las 3 familias</h3><div className="pattern-families">{families.map(family=><article key={family.name}><h4>{family.name}</h4><p className="family-question">{family.question}</p><p><b>Qué significa:</b> {family.meaning}</p><p><b>Para 14 años:</b> {family.kid}</p><p><b>Patrones:</b> {family.patterns}</p><p><b>Ejemplo:</b> {family.example}</p></article>)}</div><h3>Ejemplos claros de cada patrón</h3>{examples.map(example=><article key={example.name}><h4>{example.name}</h4><p><b>Qué hace:</b> {example.explanation}</p><p><b>Para 14 años:</b> {example.kid}</p><pre><code>{example.code}</code></pre></article>)}</section>;
}

function StudyTopicsGlossary({onTopicChange}:{onTopicChange:(topic:StudyTopic)=>void}){
 const [query,setQuery]=useState("");
 const [active,setActive]=useState(studyTopics[0].id);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?studyTopics.filter(t=>[t.title,t.summary,...t.tags,...t.points].join(" ").toLowerCase().includes(q)):studyTopics},[query]);
 const selected=filtered.find(t=>t.id===active)||filtered[0]||null;
 return <section className="study-topics"><div className="study-heading"><div><p className="eyebrow">MI GLOSARIO DE ESTUDIO</p><h2>Busca un concepto, <span>entiéndelo.</span></h2><p>Guarda aquí los temas que quieres repasar antes de una entrevista.</p></div><span className="study-count">{studyTopics.length} temas</span></div><label className="study-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar: class, struct, patrones..." aria-label="Buscar temas estudiados"/><kbd>⌘ K</kbd></label><div className="study-layout"><div className="study-list">{filtered.map(t=><button key={t.id} className={`study-topic-row ${selected?.id===t.id?"active-study-topic":""}`} onClick={()=>{setActive(t.id);onTopicChange(t)}}><span className="study-topic-icon">{t.id.includes("design")?"✦":t.id.includes("class")?"◇":t.id.includes("reference")?"↔":t.id.includes("ref")?"&": "#"}</span><span><b>{t.title}</b><small>{t.tags.join(" · ")}</small></span><span>→</span></button>)}{filtered.length===0&&<div className="study-empty">No encontré ese concepto todavía.</div>}</div>{selected&&<article className="study-detail"><p className="eyebrow">TEMA PARA REPASAR</p><h3>{selected.title}</h3><p className="study-summary">{selected.summary}</p>{selected.kid&&<div className="study-kid"><strong>Explicado para 14 años</strong><p>{selected.kid}</p></div>}<pre><code>{selected.code}</code></pre><div className="study-points">{selected.points.map((point,i)=><div key={point}><span>{i+1}</span><p>{point}</p></div>)}</div>{selected.exercises&&<div className="study-exercises"><strong>Ejercicios</strong>{selected.exercises.map((exercise,i)=><p key={exercise}><b>{i+1}.</b> {exercise}</p>)}</div>}<div className="study-trap"><strong>Trampa de entrevista</strong><p>{selected.trap}</p></div><p className="study-source">Contenido basado en documentación oficial de C# de Microsoft Learn.</p></article>}</div></section>;
}
