"use client";
import { useMemo, useState } from "react";

type StudyTopic={id:string;title:string;tags:string[];summary:string;code:string;points:string[];trap:string};

const studyTopics:StudyTopic[]=[
 {id:"class-struct-record",title:"class vs struct vs record",tags:["Tipos","POO","Entrevista"],summary:"Los tres pueden definir tipos, pero expresan semánticas diferentes: identidad y referencia, valor pequeño, o datos con igualdad por valor.",code:"class User { public int Id; }\nstruct Point { public int X, Y; }\nrecord UserDto(int Id);",points:["class es reference type y normalmente representa identidad de objeto.","struct es value type: se copia por valor y suele ser adecuado para valores pequeños.","record puede ser record class o record struct y ofrece igualdad basada en valores.","Una clase admite herencia de otra clase; un struct no hereda de clases, aunque puede implementar interfaces."],trap:"Un record no significa automáticamente que todo sea profundamente inmutable: sus propiedades y objetos internos requieren analizarse."},
 {id:"reference-value",title:"reference type vs value type",tags:["Tipos","Memoria"],summary:"La diferencia principal está en la semántica de copia. Un value type copia el valor; un reference type copia la referencia al objeto.",code:"int a = 1;\nint b = a;\nb++; // a sigue siendo 1\n\nvar x = new List<int>();\nvar y = x;\ny.Add(1); // x también ve el elemento",points:["int, bool, enum y struct son ejemplos de value types.","class, array, delegate y string son reference types.","Pasar una referencia por valor no clona automáticamente el objeto.","string es reference type, pero es inmutable; sus operaciones crean nuevas cadenas."],trap:"Reference type no significa que la variable contenga directamente el objeto; contiene una referencia al objeto."},
 {id:"pass-by-value",title:"pasar parámetros by value",tags:["Métodos","Memoria"],summary:"Por defecto, C# pasa los parámetros por valor. En un reference type se copia la referencia, por eso el método puede mutar el objeto apuntado, pero no reasignar la variable original.",code:"void Add(List<int> values)\n{\n    values.Add(10); // muta el objeto\n    values = new();  // no cambia la variable del llamador\n}",points:["Un parámetro value type por valor recibe una copia del valor.","Un parámetro reference type por valor recibe una copia de la referencia.","Mutar el objeto puede observarse fuera del método.","Reasignar el parámetro solo cambia la copia local de la referencia."],trap:"Decir simplemente que una clase siempre se pasa por referencia es impreciso; por defecto se pasa la referencia por valor."},
 {id:"ref-out",title:"ref y out",tags:["Métodos","Entrevista"],summary:"ref permite leer y modificar la variable del llamador; out permite producir un valor adicional y debe asignarse dentro del método.",code:"static void Increment(ref int value) => value++;\nstatic bool TryGet(out int value)\n{ value = 42; return true; }",points:["ref exige que la variable esté inicializada antes de la llamada.","out no exige inicialización previa, pero el método debe asignarlo antes de terminar.","TryParse usa out para devolver el resultado y bool para indicar éxito.","ref y out deben aparecer tanto en la declaración como en la llamada."],trap:"ref no es una forma de pasar cualquier objeto mágicamente: cambia el contrato para permitir reasignar la variable del llamador."},
 {id:"in-parameter",title:"parámetro in",tags:["Métodos","Value types"],summary:"in pasa un argumento por referencia de solo lectura. Puede evitar copias de structs grandes, pero el método no puede reasignar ni modificar el argumento a través de ese parámetro.",code:"static int Read(in Point point)\n    => point.X + point.Y;",points:["in comunica que el método no debe modificar el argumento.","El llamador entrega una variable compatible y el método recibe una referencia readonly.","No es lo mismo que ref: ref permite escritura.","Para tipos pequeños, la claridad suele importar más que una microoptimización."],trap:"in no convierte un reference type en inmutable; solo limita el parámetro y su asignación desde ese método."},
 {id:"boxing",title:"boxing y unboxing",tags:["Tipos","Memoria","Entrevista"],summary:"Boxing envuelve un value type dentro de un object o interfaz. Unboxing extrae el tipo compatible y puede fallar si el tipo no coincide.",code:"int number = 42;\nobject boxed = number;\nint copy = (int)boxed;",points:["Boxing crea un objeto que contiene una copia del value type.","Unboxing requiere el tipo correcto y una conversión explícita.","Las colecciones genéricas suelen evitar boxing innecesario.","El cast a un tipo incompatible produce una excepción."],trap:"Asignar un int a object no mantiene una referencia al int original; se crea una caja con una copia."},
];

export function StudyTopics(){
 const [query,setQuery]=useState("");
 const [active,setActive]=useState(studyTopics[0].id);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?studyTopics.filter(t=>[t.title,t.summary,...t.tags,...t.points].join(" ").toLowerCase().includes(q)):studyTopics},[query]);
 const selected=filtered.find(t=>t.id===active)||filtered[0]||null;
 return <section className="study-topics"><div className="study-heading"><div><p className="eyebrow">MI GLOSARIO DE ESTUDIO</p><h2>Busca un concepto, <span>entiéndelo.</span></h2><p>Guarda aquí los temas que quieres repasar antes de una entrevista.</p></div><span className="study-count">{studyTopics.length} temas</span></div><label className="study-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar: class, struct, ref, out..." aria-label="Buscar temas estudiados"/><kbd>⌘ K</kbd></label><div className="study-layout"><div className="study-list">{filtered.map(t=><button key={t.id} className={`study-topic-row ${selected?.id===t.id?"active-study-topic":""}`} onClick={()=>setActive(t.id)}><span className="study-topic-icon">{t.id.includes("class")?"◇":t.id.includes("reference")?"↔":t.id.includes("ref")?"&": "#"}</span><span><b>{t.title}</b><small>{t.tags.join(" · ")}</small></span><span>→</span></button>)}{filtered.length===0&&<div className="study-empty">No encontré ese concepto todavía.</div>}</div>{selected&&<article className="study-detail"><p className="eyebrow">TEMA PARA REPASAR</p><h3>{selected.title}</h3><p className="study-summary">{selected.summary}</p><pre><code>{selected.code}</code></pre><div className="study-points">{selected.points.map((point,i)=><div key={point}><span>{i+1}</span><p>{point}</p></div>)}</div><div className="study-trap"><strong>Trampa de entrevista</strong><p>{selected.trap}</p></div><p className="study-source">Contenido basado en documentación oficial de C# de Microsoft Learn.</p></article>}</div></section>;
}
