import type { AdvancedQuestion, AdvancedStep } from "../advanced-lessons";

// sqr rota las opciones según `shift` para que la respuesta correcta no quede
// siempre en el mismo índice (evita el patrón "la correcta siempre es A").
const sqr = (prompt: string, correct: string, wrong: [string, string, string], shift: number, why: string, code = ""): AdvancedQuestion => {
  const all = [correct, ...wrong];
  const options = all.map((_, k) => all[(k + shift) % 4]);
  const answer = (4 - shift) % 4;
  return { prompt, options, answer, why, code };
};

export const stepsM01: AdvancedStep[] = [
 {id:"m01-intro",title:"Qué son C# y .NET",summary:"C# es un lenguaje de programación fuertemente tipado creado por Microsoft. .NET es la plataforma y el conjunto de runtimes/bibliotecas que compilan y ejecutan programas escritos en C#, F# o Visual Basic.",code:"// C# es el lenguaje.\n// .NET es la plataforma que lo compila y ejecuta.\nConsole.WriteLine(\"Hola, C#\");",questions:[
  sqr("¿Qué es C#?",'Un lenguaje de programación',["Un sistema operativo","Una base de datos","Un editor de código"],0,"C# es un lenguaje de programación orientado a objetos y fuertemente tipado."),
  sqr("¿Qué es .NET en relación con C#?","La plataforma/runtime que compila y ejecuta programas en C#",["Un IDE obligatorio","Un servidor web únicamente","Un motor de bases de datos"],1,".NET provee el SDK, el runtime (CLR) y las bibliotecas base para ejecutar código C#."),
  sqr("¿Qué otros lenguajes puede compilar la plataforma .NET además de C#?","F# y Visual Basic, entre otros",["Solo C#","Python nativo","Java nativo"],2,".NET es una plataforma multilenguaje; F# y VB.NET también compilan a su runtime."),
  sqr("¿Cómo se le llama al componente de .NET que ejecuta el código compilado?","CLR (Common Language Runtime)",["JVM","Node runtime","GCC"],3,"El CLR gestiona la ejecución, memoria y tipos en tiempo de ejecución de .NET."),
  sqr("¿Qué es fuertemente tipado en el contexto de C#?","El tipo de cada valor se conoce y valida en compilación",["Los tipos se ignoran en tiempo de ejecución","Todo valor es texto internamente","Los tipos cambian libremente en runtime"],1,"El compilador de C# verifica los tipos antes de ejecutar el programa, evitando muchos errores en compilación."),
  sqr("¿Qué produce el compilador de C# a partir del código fuente?","Código intermedio (IL) que el runtime ejecuta",["Directamente instrucciones de máquina sin runtime","Un archivo de texto plano","Bytecode de otro lenguaje incompatible"],2,"El compilador de C# genera IL (Intermediate Language), que el CLR compila justo a tiempo (JIT) a código nativo."),
  sqr("¿Qué diferencia hay entre .NET Framework y .NET (moderno, desde .NET 5+)?",".NET moderno es multiplataforma (Windows, Linux, macOS); .NET Framework es solo Windows",["Son exactamente lo mismo","NET Framework es más nuevo","No existe .NET Framework"],3,".NET Framework es la versión histórica solo para Windows; .NET (5 en adelante, unificado) es open source y multiplataforma."),
  sqr("¿Qué es el SDK de .NET?","El conjunto de herramientas para compilar, ejecutar y publicar proyectos .NET",["Solo el editor de texto","Un paquete NuGet opcional","El navegador para depurar HTML"],0,"El SDK incluye el compilador, la CLI (dotnet) y las herramientas de build/publish."),
  sqr("¿Qué comando confirma que el SDK de .NET está instalado y su versión?","dotnet --version",["csc --check","dotnet install","net --sdk"],1,"dotnet --version imprime la versión del SDK activo."),
  sqr("¿Por qué es una trampa común decir que C# 'es' .NET?","Porque C# es el lenguaje y .NET es la plataforma que lo ejecuta; son cosas distintas relacionadas",["Porque son sinónimos exactos sin matices","Porque .NET es solo una librería de C#","Porque C# solo corre fuera de .NET"],2,"Distinguir lenguaje (C#) de plataforma (.NET) es clave: puedes tener otros lenguajes sobre .NET."),
 ]},
 {id:"m01-sdk-cli",title:"Instalar el SDK y usar dotnet CLI",summary:"El SDK de .NET se instala una vez por máquina y expone el comando dotnet, una CLI multiplataforma para crear, restaurar, compilar, ejecutar y publicar proyectos.",code:"dotnet --version\ndotnet new console -n HolaMundo\ncd HolaMundo\ndotnet run",questions:[
  sqr("¿Qué comando crea un nuevo proyecto de consola llamado HolaMundo?","dotnet new console -n HolaMundo",["dotnet create console HolaMundo","dotnet init console HolaMundo","dotnet console new HolaMundo"],3,"dotnet new <plantilla> -n <nombre> genera un proyecto a partir de una plantilla."),
  sqr("¿Qué hace 'dotnet run' dentro de la carpeta de un proyecto?","Restaura, compila y ejecuta la aplicación",["Solo compila sin ejecutar","Solo instala paquetes NuGet","Publica la app en producción"],0,"dotnet run compila (si es necesario) y ejecuta el proyecto en un solo paso."),
  sqr("¿Qué comando descarga las dependencias declaradas en el proyecto?","dotnet restore",["dotnet fetch","dotnet install-deps","dotnet pull"],1,"dotnet restore resuelve e instala los paquetes NuGet referenciados."),
  sqr("¿Qué comando compila el proyecto sin ejecutarlo?","dotnet build",["dotnet run --no-exec","dotnet compile","dotnet make"],2,"dotnet build genera los binarios sin lanzar la aplicación."),
  sqr("¿Qué comando lista las plantillas disponibles para 'dotnet new'?","dotnet new list",["dotnet templates","dotnet new --help-templates","dotnet list templates"],3,"dotnet new list muestra las plantillas instaladas."),
  sqr("¿Qué archivo describe cómo se compila un proyecto de consola típico?","El archivo .csproj",["package.json","Makefile","settings.json"],0,"El .csproj es el archivo de proyecto MSBuild que define SDK, TargetFramework y referencias."),
  sqr("¿Qué ocurre si ejecutas 'dotnet run' sin haber restaurado nunca los paquetes?","dotnet restaura automáticamente antes de compilar",["Falla siempre de forma irreversible","Ignora las dependencias","Solo funciona sin paquetes NuGet"],1,"dotnet run ejecuta restore y build implícitamente si es necesario."),
  sqr("¿Para qué sirve 'dotnet --list-sdks'?","Mostrar los SDKs de .NET instalados en la máquina",["Instalar un nuevo SDK","Eliminar SDKs antiguos","Listar paquetes NuGet"],2,"Este comando lista las versiones de SDK disponibles localmente."),
  sqr("¿Qué característica hace a la CLI de dotnet especialmente útil en equipos con distintos sistemas operativos?","Es multiplataforma: los mismos comandos funcionan en Windows, Linux y macOS",["Solo funciona en Windows","Requiere Visual Studio instalado siempre","Cada SO usa comandos distintos"],3,"dotnet CLI funciona igual en los tres sistemas operativos soportados, sin depender de un IDE."),
  sqr("¿Qué trampa de entrevista es común sobre 'dotnet new console'?","Genera una plantilla que puede reemplazarse o personalizarse; no es un proyecto fijo e inmutable",["Crea automáticamente una base de datos","Solo puede ejecutarse una vez por máquina","Requiere una licencia de pago"],0,"Las plantillas son puntos de partida editables; dotnet new no impone restricciones futuras sobre el código generado."),
 ]},
 {id:"m01-console-project",title:"Crear una consola y conocer el proyecto",summary:"Un proyecto de consola generado con 'dotnet new console' incluye un archivo .csproj (configuración de build) y un archivo Program.cs (código, a menudo con top-level statements en plantillas modernas).",code:"// Program.cs generado por la plantilla moderna\nConsole.WriteLine(\"Hola, mundo!\");",questions:[
  sqr("¿Qué dos archivos principales genera 'dotnet new console'?","Program.cs y el archivo .csproj",["index.html y style.css","Main.java y pom.xml","app.py y requirements.txt"],1,"El .csproj define cómo se compila el proyecto; Program.cs contiene el código de entrada."),
  sqr("¿Qué son los 'top-level statements' en Program.cs?","Código ejecutable escrito directamente en el archivo sin una clase ni un método Main explícitos",["Una forma obsoleta que ya no se genera","Código que solo funciona en pruebas unitarias","Instrucciones exclusivas de ASP.NET"],2,"Las plantillas modernas generan Program.cs con top-level statements; el compilador genera el punto de entrada implícitamente."),
  sqr("¿Qué elemento del .csproj indica la versión de .NET objetivo?","TargetFramework",["OutputType únicamente","RootNamespace","AssemblyVersion"],3,"TargetFramework (por ejemplo net10.0) determina contra qué runtime se compila el proyecto."),
  sqr("¿Qué método de la clase Console imprime texto seguido de un salto de línea?","Console.WriteLine",["Console.Print","Console.Log","Console.Out"],0,"Console.WriteLine escribe el texto y agrega un salto de línea; Console.Write no lo agrega."),
  sqr("¿Qué carpeta suele contener los binarios compilados tras un build?","bin/",["src/","dist-only/","release/ obligatoriamente"],1,"La carpeta bin (con subcarpetas Debug/Release) contiene los ensamblados generados."),
  sqr("¿Qué carpeta guarda archivos intermedios de compilación (no el resultado final)?","obj/",["bin/","out/","tmp/"],2,"obj/ contiene artefactos intermedios usados durante el build; no es el resultado final para distribuir."),
  sqr("¿Qué elemento del .csproj indica que el proyecto produce un ejecutable de consola?","OutputType=Exe",["OutputType=Library","ProjectType=Console","AssemblyType=App"],3,"OutputType Exe indica que el proyecto genera un ejecutable en lugar de una librería (Library)."),
  sqr("¿Puede un proyecto de consola referenciar paquetes NuGet externos?","Sí, agregándolos como PackageReference en el .csproj",["No, solo proyectos web pueden","Solo si se usa Visual Studio","Solo mediante copiar DLLs manualmente"],0,"Cualquier tipo de proyecto SDK-style puede declarar PackageReference para consumir paquetes NuGet."),
  sqr("¿Qué pasa si eliminas Program.cs de un proyecto de consola recién creado sin agregar otro punto de entrada?","El build falla porque no hay un punto de entrada definido",["Compila igual y no hace nada","Se genera uno automáticamente con contenido aleatorio","Se convierte en librería automáticamente"],1,"Un proyecto Exe necesita un punto de entrada (Main o top-level statements); sin él, la compilación falla."),
  sqr("¿Qué trampa de entrevista existe sobre el nombre del archivo con top-level statements?","El archivo no necesita llamarse Program.cs; solo puede haber un archivo con top-level statements por proyecto",["Debe llamarse siempre Program.cs sin excepción","Puede haber varios archivos con top-level statements","El nombre del archivo determina el namespace"],2,"Aunque la convención es Program.cs, la regla real del compilador es que solo un archivo del proyecto puede contener top-level statements."),
 ]},
 {id:"m01-build-run-publish",title:"Compilar, ejecutar y publicar",summary:"'dotnet build' compila para desarrollo, 'dotnet run' compila y ejecuta, y 'dotnet publish' genera los artefactos listos para desplegar, incluyendo opciones como self-contained o single-file.",code:"dotnet build -c Release\ndotnet publish -c Release -o ./out",questions:[
  sqr("¿Qué diferencia principal hay entre 'dotnet build' y 'dotnet publish'?","publish genera los artefactos finales listos para desplegar; build es para compilar durante desarrollo",["Son exactamente el mismo comando","build siempre publica a la nube","publish no compila el código"],3,"publish produce la salida optimizada y completa para desplegar; build es el paso habitual de desarrollo."),
  sqr("¿Qué indica la configuración 'Release' frente a 'Debug'?","Optimizaciones activadas y sin símbolos de depuración detallados, pensado para producción",["Es idéntica a Debug","Solo cambia el ícono del ejecutable","Desactiva el compilador"],0,"Release compila con optimizaciones para distribución; Debug prioriza la experiencia de depuración."),
  sqr("¿Qué significa una publicación 'self-contained'?","Incluye el runtime de .NET junto con la app, sin depender de que el runtime esté instalado en el destino",["Requiere instalar .NET manualmente en el servidor siempre","Es más pequeña que framework-dependent siempre","Solo funciona en contenedores Docker"],1,"self-contained empaqueta el runtime necesario; framework-dependent asume que el runtime ya está instalado en el destino."),
  sqr("¿Qué opción de publish reduce el resultado a un solo archivo ejecutable?","--self-contained junto con PublishSingleFile=true",["--split-files","-o single","--onefile"],2,"PublishSingleFile combina los ensamblados en un único archivo ejecutable (normalmente junto con self-contained)."),
  sqr("¿Qué parámetro de dotnet publish indica la carpeta de salida?","-o (--output)",["--target","--dest","--folder"],3,"-o (o --output) especifica dónde se colocan los artefactos publicados."),
  sqr("¿Qué es RID (Runtime Identifier) en el contexto de publish?","Un identificador de la plataforma/arquitectura destino, como linux-x64 o win-x64",["El nombre del proyecto","Una versión del lenguaje C#","Un identificador de licencia"],0,"El RID indica para qué sistema operativo y arquitectura se genera el binario nativo, relevante en self-contained o AOT."),
  sqr("¿Qué comando compila explícitamente en modo Release antes de publicar por separado?","dotnet build -c Release",["dotnet run -c Debug","dotnet restore -c Release","dotnet publish -c Debug"],1,"El flag -c (--configuration) selecciona Debug o Release para el build."),
  sqr("¿Qué ventaja tiene una publicación framework-dependent frente a self-contained?","Genera artefactos más pequeños porque reutiliza el runtime ya instalado en el destino",["Siempre es más rápida en ejecución","No requiere .NET instalado en ningún lado","Es la única opción soportada en Linux"],2,"framework-dependent depende de que el runtime .NET ya esté disponible en el destino, a cambio de un tamaño de publicación menor."),
  sqr("¿Qué comando ejecuta el ejecutable ya publicado en la carpeta de salida (sin usar 'dotnet run')?","Ejecutar directamente el binario generado, por ejemplo ./NombreApp o NombreApp.exe",["dotnet start","dotnet exec-only","dotnet open"],3,"Tras publish, el artefacto es un ejecutable (o 'dotnet NombreApp.dll' si es framework-dependent) que se lanza directamente."),
  sqr("¿Qué trampa de entrevista existe sobre 'dotnet run' en producción?","dotnet run está pensado para desarrollo; en producción se usa la salida de dotnet publish",["dotnet run es el comando recomendado para producción","publish y run son intercambiables en cualquier escenario","dotnet run genera automáticamente contenedores Docker"],0,"dotnet run recompila y ejecuta desde el código fuente; producción debe usar artefactos publicados y versionados con dotnet publish."),
 ]},
 {id:"m01-challenge",title:"Resumen y reto",summary:"Reto del módulo 1: integra la diferencia entre C# y .NET, el uso del SDK y la CLI, la estructura de un proyecto de consola y el ciclo build/run/publish.",code:"dotnet new console -n Reto\ncd Reto\ndotnet run\ndotnet publish -c Release -o ./out",questions:[
  sqr("¿Qué relación describe mejor a C# y .NET?","C# es el lenguaje; .NET es la plataforma/runtime que lo compila y ejecuta",["Son el mismo producto con nombres distintos","C# es una versión antigua de .NET",".NET es un IDE para escribir C#"],1,"C# y .NET son conceptos relacionados pero distintos: lenguaje vs. plataforma de ejecución."),
  sqr("¿Qué comando crea el proyecto de consola llamado Reto?","dotnet new console -n Reto",["dotnet console -n Reto","dotnet new -console Reto","dotnet create console -name Reto"],2,"La sintaxis correcta es 'dotnet new console -n <nombre>'."),
  sqr("¿Qué comando compila y ejecuta el proyecto en un solo paso durante desarrollo?","dotnet run",["dotnet build --exec","dotnet publish --run","dotnet start"],3,"dotnet run restaura, compila (si hace falta) y ejecuta la aplicación."),
  sqr("¿Qué archivo define el TargetFramework del proyecto Reto?","Reto.csproj",["Program.cs","appsettings.json","README.md"],0,"El archivo .csproj (aquí Reto.csproj) contiene la configuración de build, incluido TargetFramework."),
  sqr("¿Qué comando genera los artefactos finales listos para desplegar en un servidor?","dotnet publish -c Release -o ./out",["dotnet run -c Release","dotnet build --deploy","dotnet install --release"],1,"dotnet publish con -c Release y -o produce el resultado optimizado en la carpeta indicada."),
  sqr("¿Qué carpeta contiene artefactos intermedios que no deben distribuirse?","obj/",["out/","bin/Release/ tras publish","wwwroot/"],2,"obj/ son archivos intermedios de build, distintos del resultado final en bin/ o en la carpeta de publish."),
  sqr("¿Qué comando confirma qué SDKs de .NET hay instalados antes de empezar?","dotnet --list-sdks",["dotnet check","dotnet sdk-info","dotnet --sdks-installed"],3,"dotnet --list-sdks lista las versiones de SDK disponibles en la máquina."),
  sqr("¿Qué significa que una publicación sea self-contained?","Incluye el runtime .NET, sin depender de que esté preinstalado en el destino",["Requiere Visual Studio en el servidor destino","Es siempre más pequeña que framework-dependent","Solo aplica a proyectos web"],0,"self-contained empaqueta el runtime necesario junto con la app."),
  sqr("¿Qué distingue un top-level statement de un Main tradicional en Program.cs?","El compilador genera el punto de entrada implícitamente a partir del código de nivel superior",["Ambos requieren declarar Main explícitamente","top-level statements no pueden imprimir en consola","Solo funcionan en proyectos de biblioteca"],1,"Las plantillas modernas permiten escribir código ejecutable directamente sin una clase ni un método Main visibles."),
  sqr("¿Cuál es el orden lógico habitual del flujo de trabajo básico?","Crear proyecto → restaurar/compilar → ejecutar en desarrollo → publicar para producción",["Publicar → crear proyecto → ejecutar","Ejecutar → publicar → crear proyecto","Compilar → eliminar el proyecto → publicar"],2,"El ciclo natural va desde la creación del proyecto hasta la publicación final, pasando por compilación y ejecución en desarrollo."),
 ]},
];
